# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

services:
  qimsdk-docker:
    image: qimsdk-docker
    container_name: qimsdk_daisy_chain
    hostname: qimsdk_daisy_chain
    user: qimsdk
    restart: always
    environment:
      - XDG_RUNTIME_DIR=/dev/socket/weston
      - WAYLAND_DISPLAY=wayland-1
      - GST_DEBUG_NO_COLOR=1
      - GST_DEBUG=2
    command: bash qimsdk_daisy_chain.sh
    devices:
      - /dev/dri/card0
      - /dev/dri/renderD128
      - /dev/kgsl-3d0
      - /dev/video32
      - /dev/video33
      - /dev/dma_heap/system
      - /dev/dma_heap/qcom,system
      - /dev/fastrpc-cdsp
    volumes:
      - /usr/lib/libatomic.so.1:/usr/lib/libatomic.so.1
      - /usr/lib/libatomic.so.1.2.0:/usr/lib/libatomic.so.1.2.0
      - /dev/socket/weston:/dev/socket/weston
      - /opt/qti/development:/opt/qti/development
      - /usr/lib/libgbm.so:/usr/lib/libgbm.so
      - /usr/lib/libgsl.so:/usr/lib/libgsl.so
      - /usr/lib/libdmabufheap.so.0:/usr/lib/libdmabufheap.so.0
      - /usr/lib/libhta_hexagon_runtime_snpe.so:/usr/lib/libhta_hexagon_runtime_snpe.so
      - /usr/lib/libPlatformValidatorShared.so:/usr/lib/libPlatformValidatorShared.so
      - /usr/lib/libSNPE.so:/usr/lib/libSNPE.so
      - /usr/lib/libSnpeDspV66Stub.so:/usr/lib/libSnpeDspV66Stub.so
      - /usr/lib/libSnpeHta.so:/usr/lib/libSnpeHta.so
      - /usr/lib/libSnpeHtpPrepare.so:/usr/lib/libSnpeHtpPrepare.so
      - /usr/lib/libSnpeHtpV68Stub.so:/usr/lib/libSnpeHtpV68Stub.so
      - /usr/lib/libQnnChrometraceProfilingReader.so:/usr/lib/libQnnChrometraceProfilingReader.so
      - /usr/lib/libQnnGpu.so:/usr/lib/libQnnGpu.so
      - /usr/lib/libQnnHtpProfilingReader.so:/usr/lib/libQnnHtpProfilingReader.so
      - /usr/lib/libQnnCpu.so:/usr/lib/libQnnCpu.so
      - /usr/lib/libQnnDspV66Stub.so:/usr/lib/libQnnDspV66Stub.so
      - /usr/lib/libQnnHtpNetRunExtensions.so:/usr/lib/libQnnHtpNetRunExtensions.so
      - /usr/lib/libQnnHtp.so:/usr/lib/libQnnHtp.so
      - /usr/lib/libQnnJsonProfilingReader.so:/usr/lib/libQnnJsonProfilingReader.so
      - /usr/lib/libQnnDspNetRunExtensions.so:/usr/lib/libQnnDspNetRunExtensions.so
      - /usr/lib/libQnnGpuNetRunExtensions.so:/usr/lib/libQnnGpuNetRunExtensions.so
      - /usr/lib/libQnnHtpOptraceProfilingReader.so:/usr/lib/libQnnHtpOptraceProfilingReader.so
      - /usr/lib/libQnnSaver.so:/usr/lib/libQnnSaver.so
      - /usr/lib/libQnnDsp.so:/usr/lib/libQnnDsp.so
      - /usr/lib/libQnnGpuProfilingReader.so:/usr/lib/libQnnGpuProfilingReader.so
      - /usr/lib/libQnnHtpPrepare.so:/usr/lib/libQnnHtpPrepare.so
      - /usr/lib/libQnnSystem.so:/usr/lib/libQnnSystem.so
      - /usr/lib/libQnnHtpV68Stub.so:/usr/lib/libQnnHtpV68Stub.so
      - /usr/lib/rfsa/adsp/libSnpeHtpV68Skel.so:/usr/lib/rfsa/adsp/libSnpeHtpV68Skel.so
      - /usr/lib/rfsa/adsp/libQnnHtpV68Skel.so:/usr/lib/rfsa/adsp/libQnnHtpV68Skel.so
      - /usr/lib/rfsa/adsp/libQnnHtpV68.so:/usr/lib/rfsa/adsp/libQnnHtpV68.so
      - /usr/lib/rfsa/adsp/libQnnSaver.so:/usr/lib/rfsa/adsp/libQnnSaver.so
      - /usr/lib/rfsa/adsp/libQnnSystem.so:/usr/lib/rfsa/adsp/libQnnSystem.so
      - /usr/lib/libenv_time.so:/usr/lib/libenv_time.so
      - /usr/lib/libevaluation_proto.so:/usr/lib/libevaluation_proto.so
      - /usr/lib/libimage_metrics.so:/usr/lib/libimage_metrics.so
      - /usr/lib/libjpeg_internal.so:/usr/lib/libjpeg_internal.so
      - /usr/lib/libtensorflowlite_c.so:/usr/lib/libtensorflowlite_c.so
      - /usr/lib/libtf_logging.so:/usr/lib/libtf_logging.so
      - /usr/lib/libIB2C.so:/usr/lib/libIB2C.so
      - /usr/lib/libEGL_adreno.so:/usr/lib/libEGL_adreno.so
      - /usr/lib/libGLESv2_adreno.so:/usr/lib/libGLESv2_adreno.so
      - /usr/lib/libpropertyvault.so.0:/usr/lib/libpropertyvault.so.0
      - /usr/lib/libpropertyvault.so.0.0.0:/usr/lib/libpropertyvault.so.0.0.0
      - /usr/lib/libwayland-client.so.0:/usr/lib/libwayland-client.so.0
      - /usr/lib/libwayland-egl.so.1:/usr/lib/libwayland-egl.so.1
      - /usr/lib/libadreno_utils.so:/usr/lib/libadreno_utils.so
      - /usr/lib/libCB.so:/usr/lib/libCB.so
      - /usr/lib/libEGL.so:/usr/lib/libEGL.so
      - /usr/lib/libEGL.so.1:/usr/lib/libEGL.so.1
      - /usr/lib/libEGL.so.1.0:/usr/lib/libEGL.so.1.0
      - /usr/lib/libEGL.so.1.0.0:/usr/lib/libEGL.so.1.0.0
      - /usr/lib/libeglSubDriverWayland.so:/usr/lib/libeglSubDriverWayland.so
      - /usr/lib/libGLESv1_CM.so:/usr/lib/libGLESv1_CM.so
      - /usr/lib/libGLESv1_CM.so.1:/usr/lib/libGLESv1_CM.so.1
      - /usr/lib/libGLESv1_CM.so.1.0:/usr/lib/libGLESv1_CM.so.1.0
      - /usr/lib/libGLESv1_CM.so.1.0.0:/usr/lib/libGLESv1_CM.so.1.0.0
      - /usr/lib/libGLESv1_CM_adreno.so:/usr/lib/libGLESv1_CM_adreno.so
      - /usr/lib/libGLESv2.so:/usr/lib/libGLESv2.so
      - /usr/lib/libGLESv2.so.2:/usr/lib/libGLESv2.so.2
      - /usr/lib/libGLESv2.so.2.0:/usr/lib/libGLESv2.so.2.0
      - /usr/lib/libGLESv2.so.2.0.0:/usr/lib/libGLESv2.so.2.0.0
      - /usr/lib/libllvm-glnext.so:/usr/lib/libllvm-glnext.so
      - /usr/lib/libllvm-qcom.so:/usr/lib/libllvm-qcom.so
      - /usr/lib/libllvm-qgl.so:/usr/lib/libllvm-qgl.so
      - /usr/lib/libOpenCL.so:/usr/lib/libOpenCL.so
      - /usr/lib/libOpenCL_adreno.so:/usr/lib/libOpenCL_adreno.so
      - /usr/lib/libq3dtools_adreno.so:/usr/lib/libq3dtools_adreno.so
      - /usr/lib/libq3dtools_esx.so:/usr/lib/libq3dtools_esx.so
      - /usr/lib/libvulkan_adreno.so:/usr/lib/libvulkan_adreno.so
      - /usr/lib/libQnnTFLiteDelegate.so:/usr/lib/libQnnTFLiteDelegate.so
      - /usr/lib/libadsprpc.so:/usr/lib/libadsprpc.so
      - /usr/lib/libcdsprpc.so:/usr/lib/libcdsprpc.so
      - /usr/lib/libfastcvopt.so:/usr/lib/libfastcvopt.so
      - /usr/lib/rfsa/adsp/libfastcvdsp_skel.so:/usr/lib/rfsa/adsp/libfastcvdsp_skel.so
      - /usr/lib/rfsa/adsp/libfastcvadsp.so:/usr/lib/rfsa/adsp/libfastcvadsp.so
      - /usr/lib/libfastcvdsp_stub.so:/usr/lib/libfastcvdsp_stub.so
      - /usr/lib/libdmabufheap.so.0.0.0:/usr/lib/libdmabufheap.so.0.0.0
      - /usr/lib/dsp/cdsp/libc++.so.1:/usr/lib/dsp/cdsp/libc++.so.1
      - /usr/lib/dsp/cdsp/libc++abi.so.1:/usr/lib/dsp/cdsp/libc++abi.so.1
      - /opt/data:/opt/data
    network_mode: "host"