# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

services:
  redis:
    image: redis:7.2.4-alpine
    platform: arm64
    container_name: redis
    hostname: redis
    restart: always
    command: redis-server --loglevel notice
    network_mode: host
  qimsdk:
    image: softwarecenter.qualcomm.com/download/depot/services/iot-microservices/linux/qimsdk:1.0.3
    platform: arm64
    container_name: qimsdk-access-control
    hostname: qimsdk-access-control
    user: qimsdk
    restart: always
    environment:
      - XDG_RUNTIME_DIR=/dev/socket/weston
      - WAYLAND_DISPLAY=wayland-1
      - GST_DEBUG_NO_COLOR=1
      - ADSP_LIBRARY_PATH=\"/usr/lib/dsp/cdsp;/usr/lib/dsp/cdsp1;${ADSP_LIBRARY_PATH}\"
      - GST_DEBUG=2
      - INPUT_TYPE=${INPUT_TYPE:-video}
      - INPUT_URL=${INPUT_URL:-/etc/media/person_sample_video.mp4}
      - REDIS_DETECTION_CHANNEL=${REDIS_DETECTION_CHANNEL_PREFIX:-detection.face}:0
    command: bash qimsdk_access_control.sh
    volumes:
      - /etc/labels:/etc/labels
      - /etc/media:/etc/media
      - /etc/models:/etc/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - qualcomm.com/device=cdi-hw-acc
    network_mode: host
