# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_server.models.file_citation_body import FileCitationBody
from openapi_server.models.file_path import FilePath
from openapi_server.models.url_citation_body import UrlCitationBody
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

ANNOTATION_ONE_OF_SCHEMAS = ["FileCitationBody", "FilePath", "UrlCitationBody"]

class Annotation(BaseModel):
    """
    Annotation
    """
    # data type: FileCitationBody
    oneof_schema_1_validator: Optional[FileCitationBody] = None
    # data type: UrlCitationBody
    oneof_schema_2_validator: Optional[UrlCitationBody] = None
    # data type: FilePath
    oneof_schema_3_validator: Optional[FilePath] = None
    actual_instance: Optional[Union[FileCitationBody, FilePath, UrlCitationBody]] = None
    one_of_schemas: List[str] = Literal["FileCitationBody", "FilePath", "UrlCitationBody"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Annotation.model_construct()
        error_messages = []
        match = 0
        # validate data type: FileCitationBody
        if not isinstance(v, FileCitationBody):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FileCitationBody`")
        else:
            match += 1
        # validate data type: UrlCitationBody
        if not isinstance(v, UrlCitationBody):
            error_messages.append(f"Error! Input type `{type(v)}` is not `UrlCitationBody`")
        else:
            match += 1
        # validate data type: FilePath
        if not isinstance(v, FilePath):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FilePath`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Annotation with oneOf schemas: FileCitationBody, FilePath, UrlCitationBody. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Annotation with oneOf schemas: FileCitationBody, FilePath, UrlCitationBody. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into FileCitationBody
        try:
            instance.actual_instance = FileCitationBody.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into UrlCitationBody
        try:
            instance.actual_instance = UrlCitationBody.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FilePath
        try:
            instance.actual_instance = FilePath.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Annotation with oneOf schemas: FileCitationBody, FilePath, UrlCitationBody. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Annotation with oneOf schemas: FileCitationBody, FilePath, UrlCitationBody. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


