# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_server.models.computer_call_safety_check_param import ComputerCallSafetyCheckParam
from openapi_server.models.computer_screenshot_image import ComputerScreenshotImage
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ComputerCallOutputItemParam(BaseModel):
    """
    The output of a computer tool call.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The ID of the computer tool call output.")
    call_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(description="The ID of the computer tool call that produced the output.")
    type: StrictStr = Field(description="The type of the computer tool call output. Always `computer_call_output`.")
    output: ComputerScreenshotImage
    acknowledged_safety_checks: Optional[List[ComputerCallSafetyCheckParam]] = Field(default=None, description="The safety checks reported by the API that have been acknowledged by the developer.")
    status: Optional[StrictStr] = Field(default=None, description="The status of the message input. One of `in_progress`, `completed`, or `incomplete`. Populated when input items are returned via API.")
    __properties: ClassVar[List[str]] = ["id", "call_id", "type", "output", "acknowledged_safety_checks", "status"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('computer_call_output',):
            raise ValueError("must be one of enum values ('computer_call_output')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('in_progress', 'completed', 'incomplete',):
            raise ValueError("must be one of enum values ('in_progress', 'completed', 'incomplete')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ComputerCallOutputItemParam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of output
        if self.output:
            _dict['output'] = self.output.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in acknowledged_safety_checks (list)
        _items = []
        if self.acknowledged_safety_checks:
            for _item in self.acknowledged_safety_checks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['acknowledged_safety_checks'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if acknowledged_safety_checks (nullable) is None
        # and model_fields_set contains the field
        if self.acknowledged_safety_checks is None and "acknowledged_safety_checks" in self.model_fields_set:
            _dict['acknowledged_safety_checks'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ComputerCallOutputItemParam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "call_id": obj.get("call_id"),
            "type": obj.get("type") if obj.get("type") is not None else 'computer_call_output',
            "output": ComputerScreenshotImage.from_dict(obj.get("output")) if obj.get("output") is not None else None,
            "acknowledged_safety_checks": [ComputerCallSafetyCheckParam.from_dict(_item) for _item in obj.get("acknowledged_safety_checks")] if obj.get("acknowledged_safety_checks") is not None else None,
            "status": obj.get("status")
        })
        return _obj


