# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

services:
  genai_t2e:
    platform: ${TARGET_ARCH:-linux/arm64}
    image: genai_service_t2e
    container_name: genai_service_t2e
    hostname: genai_t2e
    ports:
      - "${GENAI_T2E_PORT:-9090}:9090"
    environment:
      - GENAI_T2E_PORT=9090
      - TOKENIZER_DIR=/mnt/work/models/nomic_tokenizer
    devices:
      - /dev/dma_heap/system
      - /dev/dma_heap/qcom,system
      - /dev/fastrpc-cdsp
      - /dev/fastrpc-cdsp1
    volumes:
      - /sys/firmware/devicetree/base/model:/run/device-model
      - /usr/lib/dsp/cdsp/libc++.so.1:/usr/lib/dsp/cdsp/libc++.so.1
      - /usr/lib/dsp/cdsp/libc++abi.so.1:/usr/lib/dsp/cdsp/libc++abi.so.1
      - /usr/lib/dsp/cdsp/fastrpc_shell_3:/usr/lib/dsp/cdsp/fastrpc_shell_3
      - /usr/lib/dsp/cdsp/fastrpc_shell_unsigned_3:/usr/lib/dsp/cdsp/fastrpc_shell_unsigned_3
      - /usr/lib/dsp/cdsp1/libc++.so.1:/usr/lib/dsp/cdsp1/libc++.so.1
      - /usr/lib/dsp/cdsp1/libc++abi.so.1:/usr/lib/dsp/cdsp1/libc++abi.so.1
      - /usr/lib/dsp/cdsp1/fastrpc_shell_4:/usr/lib/dsp/cdsp1/fastrpc_shell_4
      - /usr/lib/dsp/cdsp1/fastrpc_shell_unsigned_4:/usr/lib/dsp/cdsp1/fastrpc_shell_unsigned_4
      - ${T2E_MODEL_DIR:-/opt/embed_gen}:/mnt/work/models/
    command: ["hypercorn", "openapi_server.main:app", "--bind", "0.0.0.0:${GENAI_T2E_PORT}"]
