# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    Image Generation and Model Listing API

    OpenAI-compliant API for generating images using Qualcomm 9100/9075 devices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.image_response_data_inner import ImageResponseDataInner
from openapi_server.models.image_response_usage import ImageResponseUsage
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ImageResponse(BaseModel):
    """
    Represents the response returned after image generation.
    """ # noqa: E501
    background: Optional[StrictStr] = Field(default=None, description="Indicates the background setting used for the image generation.")
    created: Optional[StrictInt] = Field(default=None, description="The Unix timestamp (in seconds) of when the image was created.")
    data: Optional[List[ImageResponseDataInner]] = Field(default=None, description="The list of generated images.")
    output_format: Optional[StrictStr] = Field(default=None, description="Format of the generated image.")
    quality: Optional[StrictStr] = Field(default=None, description="Quality of the generated image.")
    size: Optional[StrictStr] = Field(default=None, description="Size of the generated image.")
    usage: Optional[ImageResponseUsage] = None
    __properties: ClassVar[List[str]] = ["background", "created", "data", "output_format", "quality", "size", "usage"]

    @field_validator('background')
    def background_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('transparent', 'opaque',):
            raise ValueError("must be one of enum values ('transparent', 'opaque')")
        return value

    @field_validator('output_format')
    def output_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('png', 'jpeg', 'webp',):
            raise ValueError("must be one of enum values ('png', 'jpeg', 'webp')")
        return value

    @field_validator('quality')
    def quality_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('low', 'medium', 'high',):
            raise ValueError("must be one of enum values ('low', 'medium', 'high')")
        return value

    @field_validator('size')
    def size_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('512 x 512',):
            raise ValueError("must be one of enum values ('512 x 512')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ImageResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item in self.data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['data'] = _items
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ImageResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "background": obj.get("background"),
            "created": obj.get("created"),
            "data": [ImageResponseDataInner.from_dict(_item) for _item in obj.get("data")] if obj.get("data") is not None else None,
            "output_format": obj.get("output_format"),
            "quality": obj.get("quality"),
            "size": obj.get("size"),
            "usage": ImageResponseUsage.from_dict(obj.get("usage")) if obj.get("usage") is not None else None
        })
        return _obj


