# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.audit_log_actor import AuditLogActor

class TestAuditLogActor(unittest.TestCase):
    """AuditLogActor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuditLogActor:
        """Test AuditLogActor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuditLogActor`
        """
        model = AuditLogActor()
        if include_optional:
            return AuditLogActor(
                type = 'session',
                session = openapi_client.models.audit_log_actor_session.AuditLogActorSession(
                    user = openapi_client.models.audit_log_actor_user.AuditLogActorUser(
                        id = '',
                        email = '', ),
                    ip_address = '', ),
                api_key = openapi_client.models.audit_log_actor_api_key.AuditLogActorApiKey(
                    id = '',
                    type = 'user',
                    user = openapi_client.models.audit_log_actor_user.AuditLogActorUser(
                        id = '',
                        email = '', ),
                    service_account = openapi_client.models.audit_log_actor_service_account.AuditLogActorServiceAccount(
                        id = '', ), )
            )
        else:
            return AuditLogActor(
        )
        """

    def testAuditLogActor(self):
        """Test AuditLogActor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
