# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.chat_completion_request_user_message import ChatCompletionRequestUserMessage

class TestChatCompletionRequestUserMessage(unittest.TestCase):
    """ChatCompletionRequestUserMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatCompletionRequestUserMessage:
        """Test ChatCompletionRequestUserMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatCompletionRequestUserMessage`
        """
        model = ChatCompletionRequestUserMessage()
        if include_optional:
            return ChatCompletionRequestUserMessage(
                content = None,
                role = 'user',
                name = ''
            )
        else:
            return ChatCompletionRequestUserMessage(
                content = None,
                role = 'user',
        )
        """

    def testChatCompletionRequestUserMessage(self):
        """Test ChatCompletionRequestUserMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
