# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.chat_completion_response_message_annotations_inner import ChatCompletionResponseMessageAnnotationsInner

class TestChatCompletionResponseMessageAnnotationsInner(unittest.TestCase):
    """ChatCompletionResponseMessageAnnotationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatCompletionResponseMessageAnnotationsInner:
        """Test ChatCompletionResponseMessageAnnotationsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatCompletionResponseMessageAnnotationsInner`
        """
        model = ChatCompletionResponseMessageAnnotationsInner()
        if include_optional:
            return ChatCompletionResponseMessageAnnotationsInner(
                type = 'url_citation',
                url_citation = openapi_client.models.chat_completion_response_message_annotations_inner_url_citation.ChatCompletionResponseMessage_annotations_inner_url_citation(
                    end_index = 56,
                    start_index = 56,
                    url = '',
                    title = '', )
            )
        else:
            return ChatCompletionResponseMessageAnnotationsInner(
                type = 'url_citation',
                url_citation = openapi_client.models.chat_completion_response_message_annotations_inner_url_citation.ChatCompletionResponseMessage_annotations_inner_url_citation(
                    end_index = 56,
                    start_index = 56,
                    url = '',
                    title = '', ),
        )
        """

    def testChatCompletionResponseMessageAnnotationsInner(self):
        """Test ChatCompletionResponseMessageAnnotationsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
