# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_batches_response import ListBatchesResponse

class TestListBatchesResponse(unittest.TestCase):
    """ListBatchesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListBatchesResponse:
        """Test ListBatchesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListBatchesResponse`
        """
        model = ListBatchesResponse()
        if include_optional:
            return ListBatchesResponse(
                data = [
                    openapi_client.models.batch.Batch(
                        id = '',
                        object = 'batch',
                        endpoint = '',
                        errors = openapi_client.models.batch_errors.Batch_errors(
                            object = '',
                            data = [
                                openapi_client.models.batch_errors_data_inner.Batch_errors_data_inner(
                                    code = '',
                                    message = '',
                                    param = '',
                                    line = 56, )
                                ], ),
                        input_file_id = '',
                        completion_window = '',
                        status = 'validating',
                        output_file_id = '',
                        error_file_id = '',
                        created_at = 56,
                        in_progress_at = 56,
                        expires_at = 56,
                        finalizing_at = 56,
                        completed_at = 56,
                        failed_at = 56,
                        expired_at = 56,
                        cancelling_at = 56,
                        cancelled_at = 56,
                        request_counts = openapi_client.models.batch_request_counts.Batch_request_counts(
                            total = 56,
                            completed = 56,
                            failed = 56, ),
                        metadata = {
                            'key' : ''
                            }, )
                    ],
                first_id = 'batch_abc123',
                last_id = 'batch_abc456',
                has_more = True,
                object = 'list'
            )
        else:
            return ListBatchesResponse(
                data = [
                    openapi_client.models.batch.Batch(
                        id = '',
                        object = 'batch',
                        endpoint = '',
                        errors = openapi_client.models.batch_errors.Batch_errors(
                            object = '',
                            data = [
                                openapi_client.models.batch_errors_data_inner.Batch_errors_data_inner(
                                    code = '',
                                    message = '',
                                    param = '',
                                    line = 56, )
                                ], ),
                        input_file_id = '',
                        completion_window = '',
                        status = 'validating',
                        output_file_id = '',
                        error_file_id = '',
                        created_at = 56,
                        in_progress_at = 56,
                        expires_at = 56,
                        finalizing_at = 56,
                        completed_at = 56,
                        failed_at = 56,
                        expired_at = 56,
                        cancelling_at = 56,
                        cancelled_at = 56,
                        request_counts = openapi_client.models.batch_request_counts.Batch_request_counts(
                            total = 56,
                            completed = 56,
                            failed = 56, ),
                        metadata = {
                            'key' : ''
                            }, )
                    ],
                has_more = True,
                object = 'list',
        )
        """

    def testListBatchesResponse(self):
        """Test ListBatchesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
