# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.audit_log_organization_updated import AuditLogOrganizationUpdated

class TestAuditLogOrganizationUpdated(unittest.TestCase):
    """AuditLogOrganizationUpdated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuditLogOrganizationUpdated:
        """Test AuditLogOrganizationUpdated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuditLogOrganizationUpdated`
        """
        model = AuditLogOrganizationUpdated()
        if include_optional:
            return AuditLogOrganizationUpdated(
                id = '',
                changes_requested = openapi_client.models.audit_log_organization_updated_changes_requested.AuditLog_organization_updated_changes_requested(
                    title = '',
                    description = '',
                    name = '',
                    settings = openapi_client.models.audit_log_organization_updated_changes_requested_settings.AuditLog_organization_updated_changes_requested_settings(
                        threads_ui_visibility = '',
                        usage_dashboard_visibility = '', ), )
            )
        else:
            return AuditLogOrganizationUpdated(
        )
        """

    def testAuditLogOrganizationUpdated(self):
        """Test AuditLogOrganizationUpdated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
