# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.modify_assistant_request import ModifyAssistantRequest

class TestModifyAssistantRequest(unittest.TestCase):
    """ModifyAssistantRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModifyAssistantRequest:
        """Test ModifyAssistantRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModifyAssistantRequest`
        """
        model = ModifyAssistantRequest()
        if include_optional:
            return ModifyAssistantRequest(
                model = None,
                reasoning_effort = 'medium',
                name = '',
                description = '',
                instructions = '',
                tools = [
                    null
                    ],
                tool_resources = openapi_client.models.modify_assistant_request_tool_resources.ModifyAssistantRequest_tool_resources(
                    code_interpreter = openapi_client.models.modify_assistant_request_tool_resources_code_interpreter.ModifyAssistantRequest_tool_resources_code_interpreter(
                        file_ids = [
                            ''
                            ], ),
                    file_search = openapi_client.models.modify_assistant_request_tool_resources_file_search.ModifyAssistantRequest_tool_resources_file_search(
                        vector_store_ids = [
                            ''
                            ], ), ),
                metadata = {
                    'key' : ''
                    },
                temperature = 1,
                top_p = 1,
                response_format = None
            )
        else:
            return ModifyAssistantRequest(
        )
        """

    def testModifyAssistantRequest(self):
        """Test ModifyAssistantRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
