# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tool import Tool

class TestTool(unittest.TestCase):
    """Tool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Tool:
        """Test Tool
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Tool`
        """
        model = Tool()
        if include_optional:
            return Tool(
                type = 'file_search',
                vector_store_ids = [
                    ''
                    ],
                max_num_results = 56,
                ranking_options = openapi_client.models.ranking_options.RankingOptions(
                    ranker = 'auto',
                    score_threshold = 1.337, ),
                filters = None,
                name = '',
                description = '',
                parameters = {
                    'key' : None
                    },
                strict = True,
                user_location = openapi_client.models.approximate_location.ApproximateLocation(
                    type = 'approximate',
                    country = '',
                    region = '',
                    city = '',
                    timezone = '', ),
                search_context_size = 'low',
                environment = 'windows',
                display_width = 56,
                display_height = 56
            )
        else:
            return Tool(
                type = 'file_search',
                vector_store_ids = [
                    ''
                    ],
                name = '',
                parameters = {
                    'key' : None
                    },
                strict = True,
                environment = 'windows',
                display_width = 56,
                display_height = 56,
        )
        """

    def testTool(self):
        """Test Tool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
