# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.computer_call_output_item_param import ComputerCallOutputItemParam

class TestComputerCallOutputItemParam(unittest.TestCase):
    """ComputerCallOutputItemParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComputerCallOutputItemParam:
        """Test ComputerCallOutputItemParam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComputerCallOutputItemParam`
        """
        model = ComputerCallOutputItemParam()
        if include_optional:
            return ComputerCallOutputItemParam(
                id = '',
                call_id = '0',
                type = 'computer_call_output',
                output = openapi_client.models.computer_screenshot_image.ComputerScreenshotImage(
                    type = 'computer_screenshot',
                    image_url = '',
                    file_id = '', ),
                acknowledged_safety_checks = [
                    openapi_client.models.computer_call_safety_check_param.ComputerCallSafetyCheckParam(
                        id = '',
                        code = '',
                        message = '', )
                    ],
                status = 'in_progress'
            )
        else:
            return ComputerCallOutputItemParam(
                call_id = '0',
                type = 'computer_call_output',
                output = openapi_client.models.computer_screenshot_image.ComputerScreenshotImage(
                    type = 'computer_screenshot',
                    image_url = '',
                    file_id = '', ),
        )
        """

    def testComputerCallOutputItemParam(self):
        """Test ComputerCallOutputItemParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
