# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.realtime_server_event_conversation_item_input_audio_transcription_delta import RealtimeServerEventConversationItemInputAudioTranscriptionDelta

class TestRealtimeServerEventConversationItemInputAudioTranscriptionDelta(unittest.TestCase):
    """RealtimeServerEventConversationItemInputAudioTranscriptionDelta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RealtimeServerEventConversationItemInputAudioTranscriptionDelta:
        """Test RealtimeServerEventConversationItemInputAudioTranscriptionDelta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RealtimeServerEventConversationItemInputAudioTranscriptionDelta`
        """
        model = RealtimeServerEventConversationItemInputAudioTranscriptionDelta()
        if include_optional:
            return RealtimeServerEventConversationItemInputAudioTranscriptionDelta(
                event_id = '',
                type = 'conversation.item.input_audio_transcription.delta',
                item_id = '',
                content_index = 56,
                delta = '',
                logprobs = [
                    openapi_client.models.log_prob_properties.LogProbProperties(
                        token = '',
                        logprob = 1.337,
                        bytes = [
                            56
                            ], )
                    ]
            )
        else:
            return RealtimeServerEventConversationItemInputAudioTranscriptionDelta(
                event_id = '',
                type = 'conversation.item.input_audio_transcription.delta',
                item_id = '',
        )
        """

    def testRealtimeServerEventConversationItemInputAudioTranscriptionDelta(self):
        """Test RealtimeServerEventConversationItemInputAudioTranscriptionDelta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
