# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.fine_tune_chat_request_input import FineTuneChatRequestInput

class TestFineTuneChatRequestInput(unittest.TestCase):
    """FineTuneChatRequestInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FineTuneChatRequestInput:
        """Test FineTuneChatRequestInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FineTuneChatRequestInput`
        """
        model = FineTuneChatRequestInput()
        if include_optional:
            return FineTuneChatRequestInput(
                messages = [
                    null
                    ],
                tools = [
                    openapi_client.models.chat_completion_tool.ChatCompletionTool(
                        type = 'function',
                        function = openapi_client.models.function_object.FunctionObject(
                            description = '',
                            name = '',
                            parameters = { },
                            strict = True, ), )
                    ],
                parallel_tool_calls = True,
                functions = [
                    openapi_client.models.chat_completion_functions.ChatCompletionFunctions(
                        description = '',
                        name = '',
                        parameters = { }, )
                    ]
            )
        else:
            return FineTuneChatRequestInput(
        )
        """

    def testFineTuneChatRequestInput(self):
        """Test FineTuneChatRequestInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
