# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.assistants_api_response_format_option import AssistantsApiResponseFormatOption

class TestAssistantsApiResponseFormatOption(unittest.TestCase):
    """AssistantsApiResponseFormatOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssistantsApiResponseFormatOption:
        """Test AssistantsApiResponseFormatOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssistantsApiResponseFormatOption`
        """
        model = AssistantsApiResponseFormatOption()
        if include_optional:
            return AssistantsApiResponseFormatOption(
                type = 'text',
                json_schema = openapi_client.models.json_schema.JSON schema(
                    description = '',
                    name = '',
                    schema = { },
                    strict = True, )
            )
        else:
            return AssistantsApiResponseFormatOption(
                type = 'text',
                json_schema = openapi_client.models.json_schema.JSON schema(
                    description = '',
                    name = '',
                    schema = { },
                    strict = True, ),
        )
        """

    def testAssistantsApiResponseFormatOption(self):
        """Test AssistantsApiResponseFormatOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
