# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.response_properties import ResponseProperties

class TestResponseProperties(unittest.TestCase):
    """ResponseProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseProperties:
        """Test ResponseProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseProperties`
        """
        model = ResponseProperties()
        if include_optional:
            return ResponseProperties(
                previous_response_id = '',
                model = llama-3.1-8,
                reasoning = openapi_client.models.reasoning.Reasoning(
                    effort = 'medium',
                    summary = 'auto',
                    generate_summary = 'auto', ),
                max_output_tokens = 56,
                instructions = '',
                text = openapi_client.models.response_properties_text.ResponseProperties_text(
                    format = null, ),
                tools = [
                    null
                    ],
                tool_choice = None,
                truncation = 'disabled'
            )
        else:
            return ResponseProperties(
        )
        """

    def testResponseProperties(self):
        """Test ResponseProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
