# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.realtime_server_event import RealtimeServerEvent

class TestRealtimeServerEvent(unittest.TestCase):
    """RealtimeServerEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RealtimeServerEvent:
        """Test RealtimeServerEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RealtimeServerEvent`
        """
        model = RealtimeServerEvent()
        if include_optional:
            return RealtimeServerEvent(
                event_id = '',
                type = 'conversation.created',
                conversation = openapi_client.models.realtime_server_event_conversation_created_conversation.RealtimeServerEventConversationCreated_conversation(
                    id = '',
                    object = '', ),
                previous_item_id = '',
                item = openapi_client.models.realtime_conversation_item.RealtimeConversationItem(
                    id = '',
                    type = 'message',
                    object = 'realtime.item',
                    status = 'completed',
                    role = 'user',
                    content = [
                        openapi_client.models.realtime_conversation_item_content_inner.RealtimeConversationItem_content_inner(
                            type = 'input_audio',
                            text = '',
                            id = '',
                            audio = '',
                            transcript = '', )
                        ],
                    call_id = '',
                    name = '',
                    arguments = '',
                    output = '', ),
                item_id = '',
                content_index = 56,
                transcript = '',
                logprobs = [
                    openapi_client.models.log_prob_properties.LogProbProperties(
                        token = '',
                        logprob = 1.337,
                        bytes = [
                            56
                            ], )
                    ],
                delta = '',
                error = openapi_client.models.realtime_server_event_error_error.RealtimeServerEventError_error(
                    type = '',
                    code = '',
                    message = '',
                    param = '',
                    event_id = '', ),
                audio_end_ms = 56,
                audio_start_ms = 56,
                rate_limits = [
                    openapi_client.models.realtime_server_event_rate_limits_updated_rate_limits_inner.RealtimeServerEventRateLimitsUpdated_rate_limits_inner(
                        name = 'requests',
                        limit = 56,
                        remaining = 56,
                        reset_seconds = 1.337, )
                    ],
                response_id = '',
                output_index = 56,
                part = openapi_client.models.realtime_server_event_response_content_part_done_part.RealtimeServerEventResponseContentPartDone_part(
                    type = 'audio',
                    text = '',
                    audio = '',
                    transcript = '', ),
                response = openapi_client.models.realtime_response.RealtimeResponse(
                    id = '',
                    object = 'realtime.response',
                    status = 'completed',
                    status_details = openapi_client.models.realtime_response_status_details.RealtimeResponse_status_details(
                        type = 'completed',
                        reason = 'turn_detected',
                        error = openapi_client.models.realtime_response_status_details_error.RealtimeResponse_status_details_error(
                            type = '',
                            code = '', ), ),
                    output = [
                        openapi_client.models.realtime_conversation_item.RealtimeConversationItem(
                            id = '',
                            type = 'message',
                            object = 'realtime.item',
                            status = 'completed',
                            role = 'user',
                            content = [
                                openapi_client.models.realtime_conversation_item_content_inner.RealtimeConversationItem_content_inner(
                                    type = 'input_audio',
                                    text = '',
                                    id = '',
                                    audio = '',
                                    transcript = '', )
                                ],
                            call_id = '',
                            name = '',
                            arguments = '', )
                        ],
                    metadata = {
                        'key' : ''
                        },
                    usage = openapi_client.models.realtime_response_usage.RealtimeResponse_usage(
                        total_tokens = 56,
                        input_tokens = 56,
                        output_tokens = 56,
                        input_token_details = openapi_client.models.realtime_response_usage_input_token_details.RealtimeResponse_usage_input_token_details(
                            cached_tokens = 56,
                            text_tokens = 56,
                            audio_tokens = 56, ),
                        output_token_details = openapi_client.models.realtime_response_usage_output_token_details.RealtimeResponse_usage_output_token_details(
                            text_tokens = 56,
                            audio_tokens = 56, ), ),
                    conversation_id = '',
                    voice = ash,
                    modalities = [
                        'text'
                        ],
                    output_audio_format = 'pcm16',
                    temperature = 1.337,
                    max_output_tokens = null, ),
                call_id = '',
                arguments = '',
                text = '',
                session = openapi_client.models.realtime_transcription_session_create_response.RealtimeTranscriptionSessionCreateResponse(
                    client_secret = openapi_client.models.realtime_transcription_session_create_response_client_secret.RealtimeTranscriptionSessionCreateResponse_client_secret(
                        value = '',
                        expires_at = 56, ),
                    modalities = [
                        'text'
                        ],
                    input_audio_format = '',
                    input_audio_transcription = openapi_client.models.realtime_transcription_session_create_response_input_audio_transcription.RealtimeTranscriptionSessionCreateResponse_input_audio_transcription(
                        model = 'llama-3.1-8',
                        language = '',
                        prompt = '', ),
                    turn_detection = openapi_client.models.realtime_session_create_response_turn_detection.RealtimeSessionCreateResponse_turn_detection(
                        type = '',
                        threshold = 1.337,
                        prefix_padding_ms = 56,
                        silence_duration_ms = 56, ), )
            )
        else:
            return RealtimeServerEvent(
                event_id = '',
                type = 'conversation.created',
                conversation = openapi_client.models.realtime_server_event_conversation_created_conversation.RealtimeServerEventConversationCreated_conversation(
                    id = '',
                    object = '', ),
                previous_item_id = '',
                item = openapi_client.models.realtime_conversation_item.RealtimeConversationItem(
                    id = '',
                    type = 'message',
                    object = 'realtime.item',
                    status = 'completed',
                    role = 'user',
                    content = [
                        openapi_client.models.realtime_conversation_item_content_inner.RealtimeConversationItem_content_inner(
                            type = 'input_audio',
                            text = '',
                            id = '',
                            audio = '',
                            transcript = '', )
                        ],
                    call_id = '',
                    name = '',
                    arguments = '',
                    output = '', ),
                item_id = '',
                content_index = 56,
                transcript = '',
                delta = '',
                error = openapi_client.models.realtime_server_event_error_error.RealtimeServerEventError_error(
                    type = '',
                    code = '',
                    message = '',
                    param = '',
                    event_id = '', ),
                audio_end_ms = 56,
                audio_start_ms = 56,
                rate_limits = [
                    openapi_client.models.realtime_server_event_rate_limits_updated_rate_limits_inner.RealtimeServerEventRateLimitsUpdated_rate_limits_inner(
                        name = 'requests',
                        limit = 56,
                        remaining = 56,
                        reset_seconds = 1.337, )
                    ],
                response_id = '',
                output_index = 56,
                part = openapi_client.models.realtime_server_event_response_content_part_done_part.RealtimeServerEventResponseContentPartDone_part(
                    type = 'audio',
                    text = '',
                    audio = '',
                    transcript = '', ),
                response = openapi_client.models.realtime_response.RealtimeResponse(
                    id = '',
                    object = 'realtime.response',
                    status = 'completed',
                    status_details = openapi_client.models.realtime_response_status_details.RealtimeResponse_status_details(
                        type = 'completed',
                        reason = 'turn_detected',
                        error = openapi_client.models.realtime_response_status_details_error.RealtimeResponse_status_details_error(
                            type = '',
                            code = '', ), ),
                    output = [
                        openapi_client.models.realtime_conversation_item.RealtimeConversationItem(
                            id = '',
                            type = 'message',
                            object = 'realtime.item',
                            status = 'completed',
                            role = 'user',
                            content = [
                                openapi_client.models.realtime_conversation_item_content_inner.RealtimeConversationItem_content_inner(
                                    type = 'input_audio',
                                    text = '',
                                    id = '',
                                    audio = '',
                                    transcript = '', )
                                ],
                            call_id = '',
                            name = '',
                            arguments = '', )
                        ],
                    metadata = {
                        'key' : ''
                        },
                    usage = openapi_client.models.realtime_response_usage.RealtimeResponse_usage(
                        total_tokens = 56,
                        input_tokens = 56,
                        output_tokens = 56,
                        input_token_details = openapi_client.models.realtime_response_usage_input_token_details.RealtimeResponse_usage_input_token_details(
                            cached_tokens = 56,
                            text_tokens = 56,
                            audio_tokens = 56, ),
                        output_token_details = openapi_client.models.realtime_response_usage_output_token_details.RealtimeResponse_usage_output_token_details(
                            text_tokens = 56,
                            audio_tokens = 56, ), ),
                    conversation_id = '',
                    voice = ash,
                    modalities = [
                        'text'
                        ],
                    output_audio_format = 'pcm16',
                    temperature = 1.337,
                    max_output_tokens = null, ),
                call_id = '',
                arguments = '',
                text = '',
                session = openapi_client.models.realtime_transcription_session_create_response.RealtimeTranscriptionSessionCreateResponse(
                    client_secret = openapi_client.models.realtime_transcription_session_create_response_client_secret.RealtimeTranscriptionSessionCreateResponse_client_secret(
                        value = '',
                        expires_at = 56, ),
                    modalities = [
                        'text'
                        ],
                    input_audio_format = '',
                    input_audio_transcription = openapi_client.models.realtime_transcription_session_create_response_input_audio_transcription.RealtimeTranscriptionSessionCreateResponse_input_audio_transcription(
                        model = 'llama-3.1-8',
                        language = '',
                        prompt = '', ),
                    turn_detection = openapi_client.models.realtime_session_create_response_turn_detection.RealtimeSessionCreateResponse_turn_detection(
                        type = '',
                        threshold = 1.337,
                        prefix_padding_ms = 56,
                        silence_duration_ms = 56, ), ),
        )
        """

    def testRealtimeServerEvent(self):
        """Test RealtimeServerEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
