# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_fine_tuning_job_events_response import ListFineTuningJobEventsResponse

class TestListFineTuningJobEventsResponse(unittest.TestCase):
    """ListFineTuningJobEventsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListFineTuningJobEventsResponse:
        """Test ListFineTuningJobEventsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListFineTuningJobEventsResponse`
        """
        model = ListFineTuningJobEventsResponse()
        if include_optional:
            return ListFineTuningJobEventsResponse(
                data = [
                    openapi_client.models.fine_tuning_job_event.FineTuningJobEvent(
                        object = 'fine_tuning.job.event',
                        id = '',
                        created_at = 56,
                        level = 'info',
                        message = '',
                        type = 'message',
                        data = openapi_client.models.data.data(), )
                    ],
                object = 'list',
                has_more = True
            )
        else:
            return ListFineTuningJobEventsResponse(
                data = [
                    openapi_client.models.fine_tuning_job_event.FineTuningJobEvent(
                        object = 'fine_tuning.job.event',
                        id = '',
                        created_at = 56,
                        level = 'info',
                        message = '',
                        type = 'message',
                        data = openapi_client.models.data.data(), )
                    ],
                object = 'list',
                has_more = True,
        )
        """

    def testListFineTuningJobEventsResponse(self):
        """Test ListFineTuningJobEventsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
