# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.completions_api import CompletionsApi


class TestCompletionsApi(unittest.TestCase):
    """CompletionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompletionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_completion(self) -> None:
        """Test case for create_completion

        Creates a completion for the provided prompt and parameters.
        """
        pass


if __name__ == '__main__':
    unittest.main()
