# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.fine_tune_preference_request_input_preferred_completion_inner import FineTunePreferenceRequestInputPreferredCompletionInner

class TestFineTunePreferenceRequestInputPreferredCompletionInner(unittest.TestCase):
    """FineTunePreferenceRequestInputPreferredCompletionInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FineTunePreferenceRequestInputPreferredCompletionInner:
        """Test FineTunePreferenceRequestInputPreferredCompletionInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FineTunePreferenceRequestInputPreferredCompletionInner`
        """
        model = FineTunePreferenceRequestInputPreferredCompletionInner()
        if include_optional:
            return FineTunePreferenceRequestInputPreferredCompletionInner(
                content = None,
                refusal = '',
                role = 'assistant',
                name = '',
                audio = openapi_client.models.chat_completion_request_assistant_message_audio.ChatCompletionRequestAssistantMessage_audio(
                    id = '', ),
                tool_calls = [
                    openapi_client.models.chat_completion_message_tool_call.ChatCompletionMessageToolCall(
                        id = '',
                        type = 'function',
                        function = openapi_client.models.chat_completion_message_tool_call_function.ChatCompletionMessageToolCall_function(
                            name = '',
                            arguments = '', ), )
                    ],
                function_call = openapi_client.models.chat_completion_request_assistant_message_function_call.ChatCompletionRequestAssistantMessage_function_call(
                    arguments = '',
                    name = '', )
            )
        else:
            return FineTunePreferenceRequestInputPreferredCompletionInner(
                role = 'assistant',
        )
        """

    def testFineTunePreferenceRequestInputPreferredCompletionInner(self):
        """Test FineTunePreferenceRequestInputPreferredCompletionInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
