# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.audit_log import AuditLog

class TestAuditLog(unittest.TestCase):
    """AuditLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuditLog:
        """Test AuditLog
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuditLog`
        """
        model = AuditLog()
        if include_optional:
            return AuditLog(
                id = '',
                type = 'api_key.created',
                effective_at = 56,
                project = openapi_client.models.audit_log_project.AuditLog_project(
                    id = '',
                    name = '', ),
                actor = openapi_client.models.audit_log_actor.AuditLogActor(
                    type = 'session',
                    session = openapi_client.models.audit_log_actor_session.AuditLogActorSession(
                        user = openapi_client.models.audit_log_actor_user.AuditLogActorUser(
                            id = '',
                            email = '', ),
                        ip_address = '', ),
                    api_key = openapi_client.models.audit_log_actor_api_key.AuditLogActorApiKey(
                        id = '',
                        type = 'user',
                        service_account = openapi_client.models.audit_log_actor_service_account.AuditLogActorServiceAccount(
                            id = '', ), ), ),
                api_key_created = openapi_client.models.audit_log_api_key_created.AuditLog_api_key_created(
                    id = '',
                    data = openapi_client.models.audit_log_api_key_created_data.AuditLog_api_key_created_data(
                        scopes = [
                            ''
                            ], ), ),
                api_key_updated = openapi_client.models.audit_log_api_key_updated.AuditLog_api_key_updated(
                    id = '',
                    changes_requested = openapi_client.models.audit_log_api_key_updated_changes_requested.AuditLog_api_key_updated_changes_requested(
                        scopes = [
                            ''
                            ], ), ),
                api_key_deleted = openapi_client.models.audit_log_api_key_deleted.AuditLog_api_key_deleted(
                    id = '', ),
                checkpoint_permission_created = openapi_client.models.audit_log_checkpoint_permission_created.AuditLog_checkpoint_permission_created(
                    id = '',
                    data = openapi_client.models.audit_log_checkpoint_permission_created_data.AuditLog_checkpoint_permission_created_data(
                        project_id = '',
                        fine_tuned_model_checkpoint = '', ), ),
                checkpoint_permission_deleted = openapi_client.models.audit_log_checkpoint_permission_deleted.AuditLog_checkpoint_permission_deleted(
                    id = '', ),
                invite_sent = openapi_client.models.audit_log_invite_sent.AuditLog_invite_sent(
                    id = '',
                    data = openapi_client.models.audit_log_invite_sent_data.AuditLog_invite_sent_data(
                        email = '',
                        role = '', ), ),
                invite_accepted = openapi_client.models.audit_log_invite_accepted.AuditLog_invite_accepted(
                    id = '', ),
                invite_deleted = openapi_client.models.audit_log_invite_accepted.AuditLog_invite_accepted(
                    id = '', ),
                login_failed = openapi_client.models.audit_log_login_failed.AuditLog_login_failed(
                    error_code = '',
                    error_message = '', ),
                logout_failed = openapi_client.models.audit_log_login_failed.AuditLog_login_failed(
                    error_code = '',
                    error_message = '', ),
                organization_updated = openapi_client.models.audit_log_organization_updated.AuditLog_organization_updated(
                    id = '',
                    changes_requested = openapi_client.models.audit_log_organization_updated_changes_requested.AuditLog_organization_updated_changes_requested(
                        title = '',
                        description = '',
                        name = '',
                        settings = openapi_client.models.audit_log_organization_updated_changes_requested_settings.AuditLog_organization_updated_changes_requested_settings(
                            threads_ui_visibility = '',
                            usage_dashboard_visibility = '', ), ), ),
                project_created = openapi_client.models.audit_log_project_created.AuditLog_project_created(
                    id = '',
                    data = openapi_client.models.audit_log_project_created_data.AuditLog_project_created_data(
                        name = '',
                        title = '', ), ),
                project_updated = openapi_client.models.audit_log_project_updated.AuditLog_project_updated(
                    id = '',
                    changes_requested = openapi_client.models.audit_log_project_updated_changes_requested.AuditLog_project_updated_changes_requested(
                        title = '', ), ),
                project_archived = openapi_client.models.audit_log_project_archived.AuditLog_project_archived(
                    id = '', ),
                rate_limit_updated = openapi_client.models.audit_log_rate_limit_updated.AuditLog_rate_limit_updated(
                    id = '',
                    changes_requested = openapi_client.models.audit_log_rate_limit_updated_changes_requested.AuditLog_rate_limit_updated_changes_requested(
                        max_requests_per_1_minute = 56,
                        max_tokens_per_1_minute = 56,
                        max_images_per_1_minute = 56,
                        max_audio_megabytes_per_1_minute = 56,
                        max_requests_per_1_day = 56,
                        batch_1_day_max_input_tokens = 56, ), ),
                rate_limit_deleted = openapi_client.models.audit_log_rate_limit_deleted.AuditLog_rate_limit_deleted(
                    id = '', ),
                service_account_created = openapi_client.models.audit_log_service_account_created.AuditLog_service_account_created(
                    id = '',
                    data = openapi_client.models.audit_log_service_account_created_data.AuditLog_service_account_created_data(
                        role = '', ), ),
                service_account_updated = openapi_client.models.audit_log_service_account_updated.AuditLog_service_account_updated(
                    id = '',
                    changes_requested = openapi_client.models.audit_log_service_account_updated_changes_requested.AuditLog_service_account_updated_changes_requested(
                        role = '', ), ),
                service_account_deleted = openapi_client.models.audit_log_service_account_deleted.AuditLog_service_account_deleted(
                    id = '', ),
                user_added = openapi_client.models.audit_log_user_added.AuditLog_user_added(
                    id = '',
                    data = openapi_client.models.audit_log_user_added_data.AuditLog_user_added_data(
                        role = '', ), ),
                user_updated = openapi_client.models.audit_log_user_updated.AuditLog_user_updated(
                    id = '',
                    changes_requested = openapi_client.models.audit_log_user_updated_changes_requested.AuditLog_user_updated_changes_requested(
                        role = '', ), ),
                user_deleted = openapi_client.models.audit_log_user_deleted.AuditLog_user_deleted(
                    id = '', ),
                certificate_created = openapi_client.models.audit_log_certificate_created.AuditLog_certificate_created(
                    id = '',
                    name = '', ),
                certificate_updated = openapi_client.models.audit_log_certificate_created.AuditLog_certificate_created(
                    id = '',
                    name = '', ),
                certificate_deleted = openapi_client.models.audit_log_certificate_deleted.AuditLog_certificate_deleted(
                    id = '',
                    name = '',
                    certificate = '', ),
                certificates_activated = openapi_client.models.audit_log_certificates_activated.AuditLog_certificates_activated(
                    certificates = [
                        openapi_client.models.audit_log_certificates_activated_certificates_inner.AuditLog_certificates_activated_certificates_inner(
                            id = '',
                            name = '', )
                        ], ),
                certificates_deactivated = openapi_client.models.audit_log_certificates_activated.AuditLog_certificates_activated(
                    certificates = [
                        openapi_client.models.audit_log_certificates_activated_certificates_inner.AuditLog_certificates_activated_certificates_inner(
                            id = '',
                            name = '', )
                        ], )
            )
        else:
            return AuditLog(
                id = '',
                type = 'api_key.created',
                effective_at = 56,
                actor = openapi_client.models.audit_log_actor.AuditLogActor(
                    type = 'session',
                    session = openapi_client.models.audit_log_actor_session.AuditLogActorSession(
                        user = openapi_client.models.audit_log_actor_user.AuditLogActorUser(
                            id = '',
                            email = '', ),
                        ip_address = '', ),
                    api_key = openapi_client.models.audit_log_actor_api_key.AuditLogActorApiKey(
                        id = '',
                        type = 'user',
                        service_account = openapi_client.models.audit_log_actor_service_account.AuditLogActorServiceAccount(
                            id = '', ), ), ),
        )
        """

    def testAuditLog(self):
        """Test AuditLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
