# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_chat_completion_stream_response import CreateChatCompletionStreamResponse

class TestCreateChatCompletionStreamResponse(unittest.TestCase):
    """CreateChatCompletionStreamResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateChatCompletionStreamResponse:
        """Test CreateChatCompletionStreamResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateChatCompletionStreamResponse`
        """
        model = CreateChatCompletionStreamResponse()
        if include_optional:
            return CreateChatCompletionStreamResponse(
                id = '',
                choices = [
                    openapi_client.models.create_chat_completion_stream_response_choices_inner.CreateChatCompletionStreamResponse_choices_inner(
                        delta = openapi_client.models.chat_completion_stream_response_delta.ChatCompletionStreamResponseDelta(
                            content = '',
                            function_call = openapi_client.models.chat_completion_stream_response_delta_function_call.ChatCompletionStreamResponseDelta_function_call(
                                arguments = '',
                                name = '', ),
                            tool_calls = [
                                openapi_client.models.chat_completion_message_tool_call_chunk.ChatCompletionMessageToolCallChunk(
                                    index = 56,
                                    id = '',
                                    type = 'function',
                                    function = openapi_client.models.chat_completion_message_tool_call_chunk_function.ChatCompletionMessageToolCallChunk_function(
                                        name = '',
                                        arguments = '', ), )
                                ],
                            role = 'developer',
                            refusal = '', ),
                        logprobs = openapi_client.models.create_chat_completion_response_choices_inner_logprobs.CreateChatCompletionResponse_choices_inner_logprobs(
                            content = [
                                openapi_client.models.chat_completion_token_logprob.ChatCompletionTokenLogprob(
                                    token = '',
                                    logprob = 1.337,
                                    bytes = [
                                        56
                                        ],
                                    top_logprobs = [
                                        openapi_client.models.chat_completion_token_logprob_top_logprobs_inner.ChatCompletionTokenLogprob_top_logprobs_inner(
                                            token = '',
                                            logprob = 1.337,
                                            bytes = [
                                                56
                                                ], )
                                        ], )
                                ],
                            refusal = [
                                openapi_client.models.chat_completion_token_logprob.ChatCompletionTokenLogprob(
                                    token = '',
                                    logprob = 1.337,
                                    bytes = ,
                                    top_logprobs = [
                                        openapi_client.models.chat_completion_token_logprob_top_logprobs_inner.ChatCompletionTokenLogprob_top_logprobs_inner(
                                            token = '',
                                            logprob = 1.337,
                                            bytes = , )
                                        ], )
                                ], ),
                        finish_reason = 'stop',
                        index = 56, )
                    ],
                created = 56,
                model = '',
                service_tier = 'auto',
                system_fingerprint = '',
                object = 'chat.completion.chunk',
                usage = openapi_client.models.completion_usage.CompletionUsage(
                    completion_tokens = 56,
                    prompt_tokens = 56,
                    total_tokens = 56,
                    completion_tokens_details = openapi_client.models.completion_usage_completion_tokens_details.CompletionUsage_completion_tokens_details(
                        accepted_prediction_tokens = 56,
                        audio_tokens = 56,
                        reasoning_tokens = 56,
                        rejected_prediction_tokens = 56, ),
                    prompt_tokens_details = openapi_client.models.completion_usage_prompt_tokens_details.CompletionUsage_prompt_tokens_details(
                        audio_tokens = 56,
                        cached_tokens = 56, ), )
            )
        else:
            return CreateChatCompletionStreamResponse(
                id = '',
                choices = [
                    openapi_client.models.create_chat_completion_stream_response_choices_inner.CreateChatCompletionStreamResponse_choices_inner(
                        delta = openapi_client.models.chat_completion_stream_response_delta.ChatCompletionStreamResponseDelta(
                            content = '',
                            function_call = openapi_client.models.chat_completion_stream_response_delta_function_call.ChatCompletionStreamResponseDelta_function_call(
                                arguments = '',
                                name = '', ),
                            tool_calls = [
                                openapi_client.models.chat_completion_message_tool_call_chunk.ChatCompletionMessageToolCallChunk(
                                    index = 56,
                                    id = '',
                                    type = 'function',
                                    function = openapi_client.models.chat_completion_message_tool_call_chunk_function.ChatCompletionMessageToolCallChunk_function(
                                        name = '',
                                        arguments = '', ), )
                                ],
                            role = 'developer',
                            refusal = '', ),
                        logprobs = openapi_client.models.create_chat_completion_response_choices_inner_logprobs.CreateChatCompletionResponse_choices_inner_logprobs(
                            content = [
                                openapi_client.models.chat_completion_token_logprob.ChatCompletionTokenLogprob(
                                    token = '',
                                    logprob = 1.337,
                                    bytes = [
                                        56
                                        ],
                                    top_logprobs = [
                                        openapi_client.models.chat_completion_token_logprob_top_logprobs_inner.ChatCompletionTokenLogprob_top_logprobs_inner(
                                            token = '',
                                            logprob = 1.337,
                                            bytes = [
                                                56
                                                ], )
                                        ], )
                                ],
                            refusal = [
                                openapi_client.models.chat_completion_token_logprob.ChatCompletionTokenLogprob(
                                    token = '',
                                    logprob = 1.337,
                                    bytes = ,
                                    top_logprobs = [
                                        openapi_client.models.chat_completion_token_logprob_top_logprobs_inner.ChatCompletionTokenLogprob_top_logprobs_inner(
                                            token = '',
                                            logprob = 1.337,
                                            bytes = , )
                                        ], )
                                ], ),
                        finish_reason = 'stop',
                        index = 56, )
                    ],
                created = 56,
                model = '',
                object = 'chat.completion.chunk',
        )
        """

    def testCreateChatCompletionStreamResponse(self):
        """Test CreateChatCompletionStreamResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
