# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vector_store_object import VectorStoreObject

class TestVectorStoreObject(unittest.TestCase):
    """VectorStoreObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VectorStoreObject:
        """Test VectorStoreObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VectorStoreObject`
        """
        model = VectorStoreObject()
        if include_optional:
            return VectorStoreObject(
                id = '',
                object = 'vector_store',
                created_at = 56,
                name = '',
                usage_bytes = 56,
                file_counts = openapi_client.models.vector_store_object_file_counts.VectorStoreObject_file_counts(
                    in_progress = 56,
                    completed = 56,
                    failed = 56,
                    cancelled = 56,
                    total = 56, ),
                status = 'expired',
                expires_after = openapi_client.models.vector_store_expiration_policy.Vector store expiration policy(
                    anchor = 'last_active_at',
                    days = 1, ),
                expires_at = 56,
                last_active_at = 56,
                metadata = {
                    'key' : ''
                    }
            )
        else:
            return VectorStoreObject(
                id = '',
                object = 'vector_store',
                created_at = 56,
                name = '',
                usage_bytes = 56,
                file_counts = openapi_client.models.vector_store_object_file_counts.VectorStoreObject_file_counts(
                    in_progress = 56,
                    completed = 56,
                    failed = 56,
                    cancelled = 56,
                    total = 56, ),
                status = 'expired',
                last_active_at = 56,
                metadata = {
                    'key' : ''
                    },
        )
        """

    def testVectorStoreObject(self):
        """Test VectorStoreObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
