# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_image_request import CreateImageRequest

class TestCreateImageRequest(unittest.TestCase):
    """CreateImageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateImageRequest:
        """Test CreateImageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateImageRequest`
        """
        model = CreateImageRequest()
        if include_optional:
            return CreateImageRequest(
                prompt = 'A cute baby sea otter',
                model = LLAMA3_1_8B`,
                n = 1,
                quality = 'auto',
                response_format = 'url',
                output_format = 'png',
                output_compression = 100,
                size = 'auto',
                moderation = 'auto',
                background = 'auto',
                style = 'vivid',
                user = 'user-1234'
            )
        else:
            return CreateImageRequest(
                prompt = 'A cute baby sea otter',
        )
        """

    def testCreateImageRequest(self):
        """Test CreateImageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
