# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_completion_response_choices_inner_logprobs import CreateCompletionResponseChoicesInnerLogprobs

class TestCreateCompletionResponseChoicesInnerLogprobs(unittest.TestCase):
    """CreateCompletionResponseChoicesInnerLogprobs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCompletionResponseChoicesInnerLogprobs:
        """Test CreateCompletionResponseChoicesInnerLogprobs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCompletionResponseChoicesInnerLogprobs`
        """
        model = CreateCompletionResponseChoicesInnerLogprobs()
        if include_optional:
            return CreateCompletionResponseChoicesInnerLogprobs(
                text_offset = [
                    56
                    ],
                token_logprobs = [
                    1.337
                    ],
                tokens = [
                    ''
                    ],
                top_logprobs = [
                    {
                        'key' : 1.337
                        }
                    ]
            )
        else:
            return CreateCompletionResponseChoicesInnerLogprobs(
        )
        """

    def testCreateCompletionResponseChoicesInnerLogprobs(self):
        """Test CreateCompletionResponseChoicesInnerLogprobs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
