# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

services:
  nginx:
    image: nginx:1.27.2-alpine
    platform: arm64
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      - ~/.configs/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ~/.configs/nginx/solutions/tripwire-analytics-api.conf:/etc/nginx/solutions/tripwire-analytics-api.conf
  mariadb:
    image: mariadb:11.6.2
    platform: arm64
    container_name: mariadb
    hostname: mariadb
    restart: always
    volumes:
      - mariadbVolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretpw
    network_mode: host
  redis:
    image: redis:7.2.4-alpine
    platform: arm64
    container_name: redis
    hostname: redis
    restart: always
    command: redis-server --loglevel notice --notify-keyspace-events Kh
    network_mode: host
  tripwire-analytics-api:
    image: artifacts.codelinaro.org/iot-solutions-microservices/tripwire-analytics-api:latest
    platform: arm64
    container_name: tripwire-analytics-api
    depends_on:
      - redis
      - mariadb
      - nginx
    restart: always
    environment:
      - redisHost=172.17.0.1
      - mariadbHost=172.17.0.1
      - mariadbPass=secretpw
      - redisTAAlertsChannel=${REDIS_ALERTS_CHANNEL:-tripwire-analytics.alerts}
      - redisTAAnalyticsChannel=${REDIS_ANALYTICS_CHANNEL:-tripwire-analytics.analytics}
      - redisCameraUpdates=${REDIS_CAMERA_UPDATES_CHANNEL:-camera-api.updates}
    expose:
      - '8082'
    network_mode: host
  tripwire-analytics-server:
    image: artifacts.codelinaro.org/iot-solutions-microservices/tripwire-analytics-server:latest
    platform: arm64
    container_name: tripwire-analytics-server
    depends_on:
      - redis
      - mariadb
    restart: always
    environment:
      - REDIS_HOST=172.17.0.1
      - REDIS_DETECTION_CHANNEL_PREFIX=${REDIS_DETECTION_CHANNEL_PREFIX:-detection.rz}
      - ALERT_CHANNEL=${REDIS_ALERTS_CHANNEL:-tripwire-analytics.alerts}
      - ANALYTICS_CHANNEL=${REDIS_ANALYTICS_CHANNEL:-tripwire-analytics.analytics}
      - UPDATES_CHANNEL=${REDIS_UPDATES_CHANNEL:-tripwire-analytics.updates}
      - MARIADB_PASSWORD=secretpw
      - MARIADB_HOST=172.17.0.1
      - MARIADB_PORT=3306
      - MARIADB_USER=root
      - MARIADB_DEFAULT=iot_solutions
      - DEFAULT_HEATMAP_TABLE=heatmap_statistics
      - DEFAULT_COUNT_TABLE=count_statistics
      - DEFAULT_HEATMAP_ROWS=64
      - DEFAULT_HEATMAP_COLS=64
    network_mode: host
  qimsdk:
    image: qimsdk:latest
    platform: arm64
    container_name: qimsdk-restricted-zone
    hostname: qimsdk-restricted-zone
    restart: always
    env_file:
      - /etc/docker/env/qimsdk.env
    volumes:
      - ${HOME}/Downloads/qimsdk_samples:/home/qimsdk/Downloads/qimsdk_samples
    command: >
      microservices-restricted-zone
      --input-type=${INPUT_TYPE:-file} --input-config=${INPUT_CONFIG:-/home/qimsdk/Downloads/qimsdk_samples/media/sample-videos/rtsp2_1_region_quarter_vertical_tripwire.ts}
      --output-type=${OUTPUT_TYPE:-rtsp} --output-config=${OUTPUT_CONFIG:-8900}
      --width=${WIDTH:-1920} --height=${HEIGHT:-1080} --framerate=${FRAMERATE:-30}
      --model-path=${MODEL_PATH_PERSON:-/home/qimsdk/Downloads/qimsdk_samples/models/foot_track_net_quantized.tflite}
      --labels-path=${LABELS_PATH_PERSON:-/home/qimsdk/Downloads/qimsdk_samples/labels/foot_track_net.json}
      --settings-path=${SETTINGS_PATH_PERSON:-/home/qimsdk/Downloads/qimsdk_samples/labels/foot_track_net_settings.json}
      --restricted-zone-boundaries=${ZONE_BOUNDARIES:-"Zones,Zone1=<<960,540>,<1920,540>,<1920,1080>,<960,1080>>;"}
      --enable-redis-meta=${ENABLE_REDIS_META_ARG:-1}
      --redis-host=${REDIS_HOST:-127.0.0.1}
      --redis-port=${REDIS_OUT_PORT:-6379}
      --redis-channel=${REDIS_DETECTION_CHANNEL_PREFIX:-detection.rz}:0
      --webrtc-id=${WEBRTC_ID:-1010}
      --no-display=${NO_DISPLAY_ARG:-0}
      --no-output-overlay=${NO_OUT_OVERLAY_ARG:-0}
      --no-debug=${NO_DEBUG_ARG:-0}
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - qualcomm.com/device=qimsdk
              capabilities:
                - hw-acc
    network_mode: host
volumes:
  mariadbVolume: null
