# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    Embeddings, Models, Health & Ping API

    OpenAI-compliant API for creating embeddings and listing models, with health and ping endpoints.

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator, model_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from openapi_server.models.create_embeddings_request_input import CreateEmbeddingsRequestInput
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CreateEmbeddingsRequest(BaseModel):
    """
    Request schema for creating embeddings.
    """ # noqa: E501
    model: Optional[StrictStr] = Field(default=None, description="ID of the model to use (e.g., nomic-embed-text,text-embedding-3-small, text-embedding-3-large, text-embedding-ada-002).")
    input: CreateEmbeddingsRequestInput
    encoding_format: Optional[StrictStr] = Field(default='float', description="Format to return the embeddings in. Defaults to float.")
    dimensions: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of dimensions for the output embeddings (supported in text-embedding-3 and later).")
    user: Optional[StrictStr] = Field(default=None, description="Unique identifier for the end-user.")
    __properties: ClassVar[List[str]] = ["model", "input", "encoding_format", "dimensions", "user"]

    @field_validator('input', mode='before')
    @classmethod
    def validate_input(cls, v):
        """Convert raw input to CreateEmbeddingsRequestInput if needed"""
        if isinstance(v, CreateEmbeddingsRequestInput):
            return v
        # If it's a raw value (string, list), wrap it in CreateEmbeddingsRequestInput
        return CreateEmbeddingsRequestInput(actual_instance=v)

    @field_validator('encoding_format')
    def encoding_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('float', 'base64',):
            raise ValueError("must be one of enum values ('float', 'base64')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreateEmbeddingsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict['input'] = self.input.to_dict()
        # set to None if encoding_format (nullable) is None
        # and model_fields_set contains the field
        if self.encoding_format is None and "encoding_format" in self.model_fields_set:
            _dict['encoding_format'] = None

        # set to None if dimensions (nullable) is None
        # and model_fields_set contains the field
        if self.dimensions is None and "dimensions" in self.model_fields_set:
            _dict['dimensions'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreateEmbeddingsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "model": obj.get("model"),
            "input": CreateEmbeddingsRequestInput.from_dict(obj.get("input")) if obj.get("input") is not None else None,
            "encoding_format": obj.get("encoding_format") if obj.get("encoding_format") is not None else 'float',
            "dimensions": obj.get("dimensions"),
            "user": obj.get("user")
        })
        return _obj
