# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    Embeddings, Models, Health & Ping API

    OpenAI-compliant API for creating embeddings and listing models, with health and ping endpoints.

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UsageRead(BaseModel):
    """
    Health status and usage metrics of a dependency or service.
    """ # noqa: E501
    date_bin: datetime
    total_generation_time: Union[StrictFloat, StrictInt]
    total_input_tokens: StrictInt
    total_output_tokens: StrictInt
    total_tokens: StrictInt
    userid: StrictStr
    __properties: ClassVar[List[str]] = ["date_bin", "total_generation_time", "total_input_tokens", "total_output_tokens", "total_tokens", "userid"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UsageRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UsageRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date_bin": obj.get("date_bin"),
            "total_generation_time": obj.get("total_generation_time"),
            "total_input_tokens": obj.get("total_input_tokens"),
            "total_output_tokens": obj.get("total_output_tokens"),
            "total_tokens": obj.get("total_tokens"),
            "userid": obj.get("userid")
        })
        return _obj


