services:
  genai-builder:
    user: root
    platform: ${HOST_ARCH}
    image: genai-builder
    container_name: genai-builder
    hostname: genai
    build:
      context: .
      dockerfile: Dockerfile
      target: genai-builder

  genai:
    user: root
    platform: ${TARGET_ARCH:-linux/arm64}
    image: genai-service
    container_name: genai-service
    hostname: genai
    build:
      context: .
      dockerfile: Dockerfile
      target: genai-service
    ports:
      - "${GENAI_PORT:-8080}:${GENAI_PORT:-8080}"
    environment:
      - GENAI_MODEL_NAME=${GENAI_MODEL_NAME}
      - GENAI_PORT=${GENAI_PORT}
    devices:
      - /dev/dma_heap/system
      - /dev/dma_heap/qcom,system
      - /dev/fastrpc-cdsp
      - /dev/fastrpc-cdsp1
    volumes:
      - /usr/lib/libdmabufheap.so.0:/usr/lib/libdmabufheap.so.0
      - /usr/lib/libcdsprpc.so:/usr/lib/libcdsprpc.so
      - ${GENAI_MODEL_DIR:-/etc/models/genie_bundle_llama3_1_8B}:/root/app/site-packages/
    command: sh -c "ln -sf /usr/include/genai_interface.h /root/app/site-packages/genai_interface.h && ln -sf /usr/lib/libllmservice.so libllmservice.so && hypercorn openapi_server.main:app --bind 0.0.0.0:${GENAI_PORT} --reload"
