# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

services:
  redis:
    image: redis:7.2.4-alpine
    platform: arm64
    container_name: redis
    hostname: redis
    restart: always
    command: redis-server --loglevel notice
    network_mode: host
  qimsdk:
    image: softwarecenter.qualcomm.com/download/depot/services/iot-microservices/linux/qimsdk:1.0.3
    platform: arm64
    container_name: qimsdk-person-foot-track
    hostname: qimsdk-person-foot-track
    user: qimsdk
    restart: always
    environment:
      - XDG_RUNTIME_DIR=/dev/socket/weston
      - WAYLAND_DISPLAY=wayland-1
      - GST_PLUGIN_SCANNER=/usr/lib/aarch64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
      - GST_DEBUG_NO_COLOR=1
      - ADSP_LIBRARY_PATH=\"/usr/lib/dsp/cdsp;/usr/lib/dsp/cdsp1;${ADSP_LIBRARY_PATH}\"
      - GST_DEBUG=2
      - INPUT_TYPE=${INPUT_TYPE:-video}
      - INPUT_URL=${INPUT_URL:-/opt/sample-videos/person_sample_video.ts}
      - REDIS_DETECTION_CHANNEL=${REDIS_DETECTION_CHANNEL_PREFIX:-detection.rz}:0
      - MODEL_PATH_PERSON=${MODEL_PATH_PERSON:-/etc/models/foot_track_net_quantized.tflite}
      - MODEL_OFFSETS_PERSON=${MODEL_OFFSETS_PERSON:-<0.0,95.0,114.0,0.0>}
      - MODEL_SCALES_PERSON=${MODEL_OFFSETS_PERSON:-<0.0037073439452797174,0.4590655267238617,2.336696147918701,0.00390625>}
      - LABELS_PATH_PERSON=${LABELS_PATH_PERSON:-/opt/labels/foot_track_net.labels}
      - REDIS_OUT_PORT=${REDIS_OUT_PORT:-6379}
      - OUT_PORT=${OUT_PORT:-8900}
    command: bash qimsdk_restricted_zone.sh
    volumes:
      - /etc/labels:/etc/labels
      - /etc/media:/etc/media
      - /etc/models:/etc/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - qualcomm.com/device=cdi-hw-acc
    network_mode: host
