# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.admin_api_key_owner import AdminApiKeyOwner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AdminApiKey(BaseModel):
    """
    Represents an individual Admin API key in an org.
    """ # noqa: E501
    object: StrictStr = Field(description="The object type, which is always `organization.admin_api_key`")
    id: StrictStr = Field(description="The identifier, which can be referenced in API endpoints")
    name: StrictStr = Field(description="The name of the API key")
    redacted_value: StrictStr = Field(description="The redacted value of the API key")
    value: Optional[StrictStr] = Field(default=None, description="The value of the API key. Only shown on create.")
    created_at: StrictInt = Field(description="The Unix timestamp (in seconds) of when the API key was created")
    last_used_at: Optional[StrictInt] = Field(description="The Unix timestamp (in seconds) of when the API key was last used")
    owner: AdminApiKeyOwner
    __properties: ClassVar[List[str]] = ["object", "id", "name", "redacted_value", "value", "created_at", "last_used_at", "owner"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminApiKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # set to None if last_used_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_used_at is None and "last_used_at" in self.model_fields_set:
            _dict['last_used_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AdminApiKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "redacted_value": obj.get("redacted_value"),
            "value": obj.get("value"),
            "created_at": obj.get("created_at"),
            "last_used_at": obj.get("last_used_at"),
            "owner": AdminApiKeyOwner.from_dict(obj.get("owner")) if obj.get("owner") is not None else None
        })
        return _obj


