# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AssistantSupportedModels(str, Enum):
    """
    AssistantSupportedModels
    """

    """
    allowed enum values
    """
    LLAMA_MINUS_3_PERIOD_1_MINUS_8 = 'llama-3.1-8'
    QWEN2_PERIOD_5_MINUS_7 = 'qwen2.5-7'
    LLAMA_MINUS_3_PERIOD_2_MINUS_3 = 'llama-3.2-3'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AssistantSupportedModels from a JSON string"""
        return cls(json.loads(json_str))


