# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_server.models.computer_use_preview_tool import ComputerUsePreviewTool
from openapi_server.models.file_search_tool import FileSearchTool
from openapi_server.models.function_tool import FunctionTool
from openapi_server.models.web_search_preview_tool import WebSearchPreviewTool
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

TOOL_ONE_OF_SCHEMAS = ["ComputerUsePreviewTool", "FileSearchTool", "FunctionTool", "WebSearchPreviewTool"]

class Tool(BaseModel):
    """
    Tool
    """
    # data type: FileSearchTool
    oneof_schema_1_validator: Optional[FileSearchTool] = None
    # data type: FunctionTool
    oneof_schema_2_validator: Optional[FunctionTool] = None
    # data type: WebSearchPreviewTool
    oneof_schema_3_validator: Optional[WebSearchPreviewTool] = None
    # data type: ComputerUsePreviewTool
    oneof_schema_4_validator: Optional[ComputerUsePreviewTool] = None
    actual_instance: Optional[Union[ComputerUsePreviewTool, FileSearchTool, FunctionTool, WebSearchPreviewTool]] = None
    one_of_schemas: List[str] = Literal["ComputerUsePreviewTool", "FileSearchTool", "FunctionTool", "WebSearchPreviewTool"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Tool.model_construct()
        error_messages = []
        match = 0
        # validate data type: FileSearchTool
        if not isinstance(v, FileSearchTool):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FileSearchTool`")
        else:
            match += 1
        # validate data type: FunctionTool
        if not isinstance(v, FunctionTool):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FunctionTool`")
        else:
            match += 1
        # validate data type: WebSearchPreviewTool
        if not isinstance(v, WebSearchPreviewTool):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WebSearchPreviewTool`")
        else:
            match += 1
        # validate data type: ComputerUsePreviewTool
        if not isinstance(v, ComputerUsePreviewTool):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ComputerUsePreviewTool`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Tool with oneOf schemas: ComputerUsePreviewTool, FileSearchTool, FunctionTool, WebSearchPreviewTool. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Tool with oneOf schemas: ComputerUsePreviewTool, FileSearchTool, FunctionTool, WebSearchPreviewTool. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into FileSearchTool
        try:
            instance.actual_instance = FileSearchTool.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FunctionTool
        try:
            instance.actual_instance = FunctionTool.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WebSearchPreviewTool
        try:
            instance.actual_instance = WebSearchPreviewTool.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ComputerUsePreviewTool
        try:
            instance.actual_instance = ComputerUsePreviewTool.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Tool with oneOf schemas: ComputerUsePreviewTool, FileSearchTool, FunctionTool, WebSearchPreviewTool. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Tool with oneOf schemas: ComputerUsePreviewTool, FileSearchTool, FunctionTool, WebSearchPreviewTool. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


