# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class WebSearchContextSize(str, Enum):
    """
    High level guidance for the amount of context window space to use for the  search. One of `low`, `medium`, or `high`. `medium` is the default.
    """

    """
    allowed enum values
    """
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebSearchContextSize from a JSON string"""
        return cls(json.loads(json_str))


