# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AuditLogEventType(str, Enum):
    """
    The event type.
    """

    """
    allowed enum values
    """
    API_KEY_DOT_CREATED = 'api_key.created'
    API_KEY_DOT_UPDATED = 'api_key.updated'
    API_KEY_DOT_DELETED = 'api_key.deleted'
    CHECKPOINT_PERMISSION_DOT_CREATED = 'checkpoint_permission.created'
    CHECKPOINT_PERMISSION_DOT_DELETED = 'checkpoint_permission.deleted'
    INVITE_DOT_SENT = 'invite.sent'
    INVITE_DOT_ACCEPTED = 'invite.accepted'
    INVITE_DOT_DELETED = 'invite.deleted'
    LOGIN_DOT_SUCCEEDED = 'login.succeeded'
    LOGIN_DOT_FAILED = 'login.failed'
    LOGOUT_DOT_SUCCEEDED = 'logout.succeeded'
    LOGOUT_DOT_FAILED = 'logout.failed'
    ORGANIZATION_DOT_UPDATED = 'organization.updated'
    PROJECT_DOT_CREATED = 'project.created'
    PROJECT_DOT_UPDATED = 'project.updated'
    PROJECT_DOT_ARCHIVED = 'project.archived'
    SERVICE_ACCOUNT_DOT_CREATED = 'service_account.created'
    SERVICE_ACCOUNT_DOT_UPDATED = 'service_account.updated'
    SERVICE_ACCOUNT_DOT_DELETED = 'service_account.deleted'
    RATE_LIMIT_DOT_UPDATED = 'rate_limit.updated'
    RATE_LIMIT_DOT_DELETED = 'rate_limit.deleted'
    USER_DOT_ADDED = 'user.added'
    USER_DOT_UPDATED = 'user.updated'
    USER_DOT_DELETED = 'user.deleted'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AuditLogEventType from a JSON string"""
        return cls(json.loads(json_str))


