# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Includable(str, Enum):
    """
    Specify additional output data to include in the model response. Currently supported values are: - `file_search_call.results`: Include the search results of   the file search tool call. - `message.input_image.image_url`: Include image urls from the input message. - `computer_call_output.output.image_url`: Include image urls from the computer call output.
    """

    """
    allowed enum values
    """
    FILE_SEARCH_CALL_DOT_RESULTS = 'file_search_call.results'
    MESSAGE_DOT_INPUT_IMAGE_DOT_IMAGE_URL = 'message.input_image.image_url'
    COMPUTER_CALL_OUTPUT_DOT_OUTPUT_DOT_IMAGE_URL = 'computer_call_output.output.image_url'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Includable from a JSON string"""
        return cls(json.loads(json_str))


