# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from openapi_client.models.computer_tool_call import ComputerToolCall
from openapi_client.models.file_search_tool_call import FileSearchToolCall
from openapi_client.models.function_tool_call import FunctionToolCall
from openapi_client.models.output_message import OutputMessage
from openapi_client.models.reasoning_item import ReasoningItem
from openapi_client.models.web_search_tool_call import WebSearchToolCall
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

OUTPUTITEM_ANY_OF_SCHEMAS = ["ComputerToolCall", "FileSearchToolCall", "FunctionToolCall", "OutputMessage", "ReasoningItem", "WebSearchToolCall"]

class OutputItem(BaseModel):
    """
    OutputItem
    """

    # data type: OutputMessage
    anyof_schema_1_validator: Optional[OutputMessage] = None
    # data type: FileSearchToolCall
    anyof_schema_2_validator: Optional[FileSearchToolCall] = None
    # data type: FunctionToolCall
    anyof_schema_3_validator: Optional[FunctionToolCall] = None
    # data type: WebSearchToolCall
    anyof_schema_4_validator: Optional[WebSearchToolCall] = None
    # data type: ComputerToolCall
    anyof_schema_5_validator: Optional[ComputerToolCall] = None
    # data type: ReasoningItem
    anyof_schema_6_validator: Optional[ReasoningItem] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[ComputerToolCall, FileSearchToolCall, FunctionToolCall, OutputMessage, ReasoningItem, WebSearchToolCall]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "ComputerToolCall", "FileSearchToolCall", "FunctionToolCall", "OutputMessage", "ReasoningItem", "WebSearchToolCall" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = OutputItem.model_construct()
        error_messages = []
        # validate data type: OutputMessage
        if not isinstance(v, OutputMessage):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OutputMessage`")
        else:
            return v

        # validate data type: FileSearchToolCall
        if not isinstance(v, FileSearchToolCall):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FileSearchToolCall`")
        else:
            return v

        # validate data type: FunctionToolCall
        if not isinstance(v, FunctionToolCall):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FunctionToolCall`")
        else:
            return v

        # validate data type: WebSearchToolCall
        if not isinstance(v, WebSearchToolCall):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WebSearchToolCall`")
        else:
            return v

        # validate data type: ComputerToolCall
        if not isinstance(v, ComputerToolCall):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ComputerToolCall`")
        else:
            return v

        # validate data type: ReasoningItem
        if not isinstance(v, ReasoningItem):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ReasoningItem`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in OutputItem with anyOf schemas: ComputerToolCall, FileSearchToolCall, FunctionToolCall, OutputMessage, ReasoningItem, WebSearchToolCall. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[OutputMessage] = None
        try:
            instance.actual_instance = OutputMessage.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[FileSearchToolCall] = None
        try:
            instance.actual_instance = FileSearchToolCall.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[FunctionToolCall] = None
        try:
            instance.actual_instance = FunctionToolCall.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[WebSearchToolCall] = None
        try:
            instance.actual_instance = WebSearchToolCall.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[ComputerToolCall] = None
        try:
            instance.actual_instance = ComputerToolCall.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[ReasoningItem] = None
        try:
            instance.actual_instance = ReasoningItem.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into OutputItem with anyOf schemas: ComputerToolCall, FileSearchToolCall, FunctionToolCall, OutputMessage, ReasoningItem, WebSearchToolCall. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ComputerToolCall, FileSearchToolCall, FunctionToolCall, OutputMessage, ReasoningItem, WebSearchToolCall]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


