# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from fastapi import FastAPI, Request
from contextlib import asynccontextmanager

from openapi_server.apis.chat_api import router as ChatApiRouter
from openapi_server.apis.health_api import router as HealthApiRouter
from openapi_server.apis.ping_api import router as PingApiRouter
from openapi_server.apis.models_api import router as ModelApiRouter
from openapi_server.apis.metrics_api import router as MetricsApiRouter
import logging
from openapi_server.version import __version__
from openapi_server.logger.logger_config import LoggerConfig
from openapi_server.managers.model_config_manager import ModelConfigManager
from openapi_server.thread_pool import (
    initialize_vlm_thread_pool,
    shutdown_vlm_thread_pool,
    initialize_vlm_operation_lock,
    clear_preinit_vlm_objects
)
from starlette.middleware.base import BaseHTTPMiddleware
import yaml
import os

LoggerConfig.initialize()
logger = LoggerConfig.get_logger(__name__)

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Lifespan context manager for FastAPI application.
    Manages the lifecycle of application resources including:
    - VLM thread pool for blocking operations
    - VLM execution thread for thread-affinity operations
    - VLM operation lock for serializing requests
    - RequestQueueManager for ADHOC_MODE DSP serialization
    - ModelConfigManager for model configuration

    VLM initialization is controlled by the ENABLE_VLM environment variable.
    Set ENABLE_VLM=true to enable VLM support, or ENABLE_VLM=false to disable it.
    """
    # Check if VLM should be enabled via environment variable
    import os
    enable_vlm = os.getenv("ENABLE_VLM", "true").lower() in ("true", "1", "yes", "on")

    vlm_initialized = False
    queue_manager_started = False

    # ========== STARTUP ==========

    logger.info(f"Starting Gen-AI Microservice - Version {__version__}")

    # Initialize ModelConfigManager to load configuration
    try:
        config_manager = ModelConfigManager()
        models = config_manager.get_available_models()
        logger.info(f"Loaded {len(models)} models from configuration")
        for model in models:
            logger.info(f"  - {model['id']}: {model.get('display_name', 'N/A')}")
    except Exception as e:
        logger.error(f"Failed to initialize ModelConfigManager: {e}", exc_info=True)
        logger.warning("Service will continue with fallback configuration")

    # Initialize SystemResourceManager with configuration
    try:
        from openapi_server.managers.system_resource_manager import SystemResourceManager
        from openapi_server.impl.constant import SystemResourceConstants

        resource_manager = SystemResourceManager()

        # Get system config from constants
        memory_headroom = SystemResourceConstants.MEMORY_HEADROOM_PERCENT
        guardrails_enabled = SystemResourceConstants.ENABLE_RESOURCE_GUARDRAILS

        # Configure resource manager
        resource_manager.configure(
            memory_headroom_percent=memory_headroom,
            enable_guardrails=guardrails_enabled
        )

        # Log memory statistics
        mem_stats = resource_manager.get_memory_stats()
        logger.info(f"System Memory: {mem_stats['total_memory_mb']}MB total, "
                   f"{mem_stats['available_memory_mb']}MB available")
        logger.info(f"Resource Guardrails: {'Enabled' if guardrails_enabled else 'Disabled'} "
                   f"(headroom: {memory_headroom}%)")
    except Exception as e:
        logger.error(f"Failed to initialize SystemResourceManager: {e}", exc_info=True)
        logger.warning("Service will continue without resource guardrails")

    if enable_vlm:
        # Startup - Initialize VLM Resources
        logger.info("=== VLM Enabled - Initializing VLM Resources ===")

        # Initialize thread pool for general blocking operations
        logger.info("Initializing VLM thread pool with 4 workers")
        initialize_vlm_thread_pool(max_workers=4)
        logger.info("VLM thread pool initialized")

        # Initialize VLM operation lock for serializing VLM requests
        logger.info("Initializing VLM operation lock")
        initialize_vlm_operation_lock()
        logger.info("VLM operation lock initialized")

        vlm_initialized = True
        logger.info("=== VLM Resources Initialized ===")
    else:
        logger.info("=== VLM Disabled - Skipping VLM initialization (ENABLE_VLM=false) ===")

    # Initialize RequestQueueManager for ADHOC_MODE
    from openapi_server.impl.constant import ADHOC_MODE
    if ADHOC_MODE:
        from openapi_server.managers.request_queue_manager import RequestQueueManager
        queue_manager = RequestQueueManager.get_instance()
        await queue_manager.start_worker()
        queue_manager_started = True
        logger.info("✓ RequestQueueManager started for ADHOC_MODE")
    else:
        logger.info("RequestQueueManager disabled (ADHOC_MODE=false)")

    yield

    # ========== SHUTDOWN ==========

    logger.info("Shutting down Gen-AI Microservice")

    # Shutdown inference process managers to free DSP/NPU resources
    logger.info("=== Shutting Down Inference Process Managers ===")

    # Shutdown LLM process manager
    try:
        from openapi_server.impl.genie_wrapper.llm_process_manager import LLMProcessManager
        llm_manager = LLMProcessManager.get_instance()
        if llm_manager.process and llm_manager.process.poll() is None:
            logger.info("Shutting down LLM process manager...")
            llm_manager.shutdown()
            logger.info("✓ LLM process manager shut down")
        else:
            logger.info("LLM process manager not running, skipping shutdown")
    except Exception as e:
        logger.error(f"Error shutting down LLM process manager: {e}", exc_info=True)

    # Shutdown VLM process manager
    try:
        from openapi_server.impl.genie_wrapper.vlm_process_manager import VLMProcessManager
        vlm_manager = VLMProcessManager.get_instance()
        if vlm_manager.process and vlm_manager.process.poll() is None:
            logger.info("Shutting down VLM process manager...")
            vlm_manager.shutdown()
            logger.info("✓ VLM process manager shut down")
        else:
            logger.info("VLM process manager not running, skipping shutdown")
    except Exception as e:
        logger.error(f"Error shutting down VLM process manager: {e}", exc_info=True)

    logger.info("=== Inference Process Managers Shut Down ===")

    # Shutdown RequestQueueManager if enabled
    if queue_manager_started:
        from openapi_server.managers.request_queue_manager import RequestQueueManager
        queue_manager = RequestQueueManager.get_instance()
        await queue_manager.shutdown()
        logger.info("✓ RequestQueueManager shut down")

    # Shutdown VLM resources - Only if VLM was initialized
    if vlm_initialized:
        logger.info("=== Shutting Down VLM Resources ===")

        # Shutdown thread pool
        logger.info("Shutting down VLM thread pool...")
        shutdown_vlm_thread_pool(wait=True)
        logger.info("VLM thread pool shut down")

        # Clear pre-initialized VLM objects
        logger.info("Clearing pre-initialized VLM objects...")
        clear_preinit_vlm_objects()
        logger.info("Pre-initialized VLM objects cleared")

        logger.info("=== VLM Resources Shut Down ===")
    else:
        logger.info("=== VLM was not initialized - No VLM resources to shut down ===")

app = FastAPI(
    title="IOT Solutions - Gen-AI Microservice APIs",
    description="These REST APIs provide the capability to run inference on Qualcomm 9100 devices.",
    version=__version__,
    lifespan=lifespan,  # Add lifespan context manager
)

base_dir = os.getenv("VLM_SITE_PACKAGES_PATH")
file_path = os.path.join(base_dir, "openapi.yaml")

# Load Custom Open AI API Schema
with open(file_path, "r") as f:
    openapi_schema = yaml.safe_load(f)

app.openapi_schema = openapi_schema

class LoggingMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        body = await request.body()
        logger.debug(f"Incoming request: {request.method} {request.url}")
        logger.debug(f"Request body: {body.decode('utf-8')}")
        # Re-create request with the same body for downstream
        request = Request(request.scope, receive=lambda: {"type": "http.request", "body": body})
        response = await call_next(request)
        return response
app.add_middleware(LoggingMiddleware)

app.include_router(ModelApiRouter)
app.include_router(ChatApiRouter)
app.include_router(HealthApiRouter)
app.include_router(PingApiRouter)
app.include_router(MetricsApiRouter)
