# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.realtime_client_event_response_create import RealtimeClientEventResponseCreate

class TestRealtimeClientEventResponseCreate(unittest.TestCase):
    """RealtimeClientEventResponseCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RealtimeClientEventResponseCreate:
        """Test RealtimeClientEventResponseCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RealtimeClientEventResponseCreate`
        """
        model = RealtimeClientEventResponseCreate()
        if include_optional:
            return RealtimeClientEventResponseCreate(
                event_id = '',
                type = 'response.create',
                response = openapi_client.models.realtime_response_create_params.RealtimeResponseCreateParams(
                    modalities = [
                        'text'
                        ],
                    instructions = '',
                    voice = ash,
                    output_audio_format = 'pcm16',
                    tools = [
                        openapi_client.models.realtime_response_create_params_tools_inner.RealtimeResponseCreateParams_tools_inner(
                            type = 'function',
                            name = '',
                            description = '',
                            parameters = openapi_client.models.parameters.parameters(), )
                        ],
                    tool_choice = '',
                    temperature = 1.337,
                    max_response_output_tokens = null,
                    conversation = null,
                    metadata = {
                        'key' : ''
                        },
                    input = [
                        openapi_client.models.realtime_conversation_item_with_reference.RealtimeConversationItemWithReference(
                            id = '',
                            type = 'message',
                            object = 'realtime.item',
                            status = 'completed',
                            role = 'user',
                            content = [
                                openapi_client.models.realtime_conversation_item_content_inner.RealtimeConversationItem_content_inner(
                                    type = 'input_audio',
                                    text = '',
                                    id = '',
                                    audio = '',
                                    transcript = '', )
                                ],
                            call_id = '',
                            name = '',
                            arguments = '',
                            output = '', )
                        ], )
            )
        else:
            return RealtimeClientEventResponseCreate(
                type = 'response.create',
        )
        """

    def testRealtimeClientEventResponseCreate(self):
        """Test RealtimeClientEventResponseCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
