# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.message_stream_event_one_of1 import MessageStreamEventOneOf1

class TestMessageStreamEventOneOf1(unittest.TestCase):
    """MessageStreamEventOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageStreamEventOneOf1:
        """Test MessageStreamEventOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageStreamEventOneOf1`
        """
        model = MessageStreamEventOneOf1()
        if include_optional:
            return MessageStreamEventOneOf1(
                event = 'thread.message.in_progress',
                data = openapi_client.models.the_message_object.The message object(
                    id = '',
                    object = 'thread.message',
                    created_at = 56,
                    thread_id = '',
                    status = 'in_progress',
                    incomplete_details = openapi_client.models.message_object_incomplete_details.MessageObject_incomplete_details(
                        reason = 'content_filter', ),
                    completed_at = 56,
                    incomplete_at = 56,
                    role = 'user',
                    content = [
                        null
                        ],
                    assistant_id = '',
                    run_id = '',
                    attachments = [
                        openapi_client.models.create_message_request_attachments_inner.CreateMessageRequest_attachments_inner(
                            file_id = '',
                            tools = [
                                null
                                ], )
                        ],
                    metadata = {
                        'key' : ''
                        }, )
            )
        else:
            return MessageStreamEventOneOf1(
                event = 'thread.message.in_progress',
                data = openapi_client.models.the_message_object.The message object(
                    id = '',
                    object = 'thread.message',
                    created_at = 56,
                    thread_id = '',
                    status = 'in_progress',
                    incomplete_details = openapi_client.models.message_object_incomplete_details.MessageObject_incomplete_details(
                        reason = 'content_filter', ),
                    completed_at = 56,
                    incomplete_at = 56,
                    role = 'user',
                    content = [
                        null
                        ],
                    assistant_id = '',
                    run_id = '',
                    attachments = [
                        openapi_client.models.create_message_request_attachments_inner.CreateMessageRequest_attachments_inner(
                            file_id = '',
                            tools = [
                                null
                                ], )
                        ],
                    metadata = {
                        'key' : ''
                        }, ),
        )
        """

    def testMessageStreamEventOneOf1(self):
        """Test MessageStreamEventOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
