# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_resource import ItemResource

class TestItemResource(unittest.TestCase):
    """ItemResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemResource:
        """Test ItemResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemResource`
        """
        model = ItemResource()
        if include_optional:
            return ItemResource(
                type = 'message',
                role = 'assistant',
                status = 'in_progress',
                content = [
                    null
                    ],
                id = '',
                queries = [
                    ''
                    ],
                results = [
                    openapi_client.models.file_search_tool_call_results_inner.FileSearchToolCall_results_inner(
                        file_id = '',
                        text = '',
                        filename = '',
                        attributes = {
                            'key' : null
                            },
                        score = 1.337, )
                    ],
                call_id = '',
                action = None,
                pending_safety_checks = [
                    openapi_client.models.computer_tool_call_safety_check.ComputerToolCallSafetyCheck(
                        id = '',
                        code = '',
                        message = '', )
                    ],
                acknowledged_safety_checks = [
                    openapi_client.models.computer_tool_call_safety_check.ComputerToolCallSafetyCheck(
                        id = '',
                        code = '',
                        message = '', )
                    ],
                output = '',
                name = '',
                arguments = ''
            )
        else:
            return ItemResource(
                type = 'message',
                role = 'assistant',
                status = 'in_progress',
                content = [
                    null
                    ],
                id = '',
                queries = [
                    ''
                    ],
                call_id = '',
                action = None,
                pending_safety_checks = [
                    openapi_client.models.computer_tool_call_safety_check.ComputerToolCallSafetyCheck(
                        id = '',
                        code = '',
                        message = '', )
                    ],
                output = '',
                name = '',
                arguments = '',
        )
        """

    def testItemResource(self):
        """Test ItemResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
