# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.assistant_tools_file_search import AssistantToolsFileSearch

class TestAssistantToolsFileSearch(unittest.TestCase):
    """AssistantToolsFileSearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssistantToolsFileSearch:
        """Test AssistantToolsFileSearch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssistantToolsFileSearch`
        """
        model = AssistantToolsFileSearch()
        if include_optional:
            return AssistantToolsFileSearch(
                type = 'file_search',
                file_search = openapi_client.models.assistant_tools_file_search_file_search.AssistantToolsFileSearch_file_search(
                    max_num_results = 1,
                    ranking_options = openapi_client.models.file_search_tool_call_ranking_options.File search tool call ranking options(
                        ranker = 'auto',
                        score_threshold = 0, ), )
            )
        else:
            return AssistantToolsFileSearch(
                type = 'file_search',
        )
        """

    def testAssistantToolsFileSearch(self):
        """Test AssistantToolsFileSearch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
