# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_moderation_request_input_one_of_inner import CreateModerationRequestInputOneOfInner

class TestCreateModerationRequestInputOneOfInner(unittest.TestCase):
    """CreateModerationRequestInputOneOfInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateModerationRequestInputOneOfInner:
        """Test CreateModerationRequestInputOneOfInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateModerationRequestInputOneOfInner`
        """
        model = CreateModerationRequestInputOneOfInner()
        if include_optional:
            return CreateModerationRequestInputOneOfInner(
                type = 'image_url',
                image_url = openapi_client.models.create_moderation_request_input_one_of_inner_one_of_image_url.CreateModerationRequest_input_oneOf_inner_oneOf_image_url(
                    url = 'https://example.com/image.jpg', ),
                text = 'I want to kill them'
            )
        else:
            return CreateModerationRequestInputOneOfInner(
                type = 'image_url',
                image_url = openapi_client.models.create_moderation_request_input_one_of_inner_one_of_image_url.CreateModerationRequest_input_oneOf_inner_oneOf_image_url(
                    url = 'https://example.com/image.jpg', ),
                text = 'I want to kill them',
        )
        """

    def testCreateModerationRequestInputOneOfInner(self):
        """Test CreateModerationRequestInputOneOfInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
