# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.reasoning_item import ReasoningItem

class TestReasoningItem(unittest.TestCase):
    """ReasoningItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReasoningItem:
        """Test ReasoningItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReasoningItem`
        """
        model = ReasoningItem()
        if include_optional:
            return ReasoningItem(
                type = 'reasoning',
                id = '',
                summary = [
                    openapi_client.models.reasoning_item_summary_inner.ReasoningItem_summary_inner(
                        type = 'summary_text',
                        text = '', )
                    ],
                status = 'in_progress'
            )
        else:
            return ReasoningItem(
                type = 'reasoning',
                id = '',
                summary = [
                    openapi_client.models.reasoning_item_summary_inner.ReasoningItem_summary_inner(
                        type = 'summary_text',
                        text = '', )
                    ],
        )
        """

    def testReasoningItem(self):
        """Test ReasoningItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
