# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.input_content import InputContent

class TestInputContent(unittest.TestCase):
    """InputContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InputContent:
        """Test InputContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InputContent`
        """
        model = InputContent()
        if include_optional:
            return InputContent(
                type = 'input_text',
                text = '',
                image_url = '',
                file_id = '',
                detail = 'low',
                filename = '',
                file_data = ''
            )
        else:
            return InputContent(
                type = 'input_text',
                text = '',
                detail = 'low',
        )
        """

    def testInputContent(self):
        """Test InputContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
