# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.run_step_delta_step_details_tool_calls_code_object import RunStepDeltaStepDetailsToolCallsCodeObject

class TestRunStepDeltaStepDetailsToolCallsCodeObject(unittest.TestCase):
    """RunStepDeltaStepDetailsToolCallsCodeObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunStepDeltaStepDetailsToolCallsCodeObject:
        """Test RunStepDeltaStepDetailsToolCallsCodeObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunStepDeltaStepDetailsToolCallsCodeObject`
        """
        model = RunStepDeltaStepDetailsToolCallsCodeObject()
        if include_optional:
            return RunStepDeltaStepDetailsToolCallsCodeObject(
                index = 56,
                id = '',
                type = 'code_interpreter',
                code_interpreter = openapi_client.models.run_step_delta_step_details_tool_calls_code_object_code_interpreter.RunStepDeltaStepDetailsToolCallsCodeObject_code_interpreter(
                    input = '',
                    outputs = [
                        openapi_client.models.run_step_delta_step_details_tool_calls_code_object_code_interpreter_outputs_inner.RunStepDeltaStepDetailsToolCallsCodeObject_code_interpreter_outputs_inner()
                        ], )
            )
        else:
            return RunStepDeltaStepDetailsToolCallsCodeObject(
                index = 56,
                type = 'code_interpreter',
        )
        """

    def testRunStepDeltaStepDetailsToolCallsCodeObject(self):
        """Test RunStepDeltaStepDetailsToolCallsCodeObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
