# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.response_stream_event import ResponseStreamEvent

class TestResponseStreamEvent(unittest.TestCase):
    """ResponseStreamEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseStreamEvent:
        """Test ResponseStreamEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseStreamEvent`
        """
        model = ResponseStreamEvent()
        if include_optional:
            return ResponseStreamEvent(
                type = 'response.audio.delta',
                delta = '',
                output_index = 56,
                code = '',
                code_interpreter_call = openapi_client.models.code_interpreter_tool_call.Code interpreter tool call(
                    id = '',
                    type = 'code_interpreter_call',
                    code = '',
                    status = 'in_progress',
                    results = [
                        null
                        ], ),
                response = None,
                item_id = '',
                content_index = 56,
                part = openapi_client.models.response_reasoning_summary_part_done_event_part.ResponseReasoningSummaryPartDoneEvent_part(
                    type = 'summary_text',
                    text = '', ),
                message = '',
                param = '',
                arguments = '',
                item = None,
                summary_index = 56,
                text = '',
                refusal = '',
                annotation_index = 56,
                annotation = None
            )
        else:
            return ResponseStreamEvent(
                type = 'response.audio.delta',
                delta = '',
                output_index = 56,
                code = '',
                code_interpreter_call = openapi_client.models.code_interpreter_tool_call.Code interpreter tool call(
                    id = '',
                    type = 'code_interpreter_call',
                    code = '',
                    status = 'in_progress',
                    results = [
                        null
                        ], ),
                response = None,
                item_id = '',
                content_index = 56,
                part = openapi_client.models.response_reasoning_summary_part_done_event_part.ResponseReasoningSummaryPartDoneEvent_part(
                    type = 'summary_text',
                    text = '', ),
                message = '',
                param = '',
                arguments = '',
                item = None,
                summary_index = 56,
                text = '',
                refusal = '',
                annotation_index = 56,
                annotation = None,
        )
        """

    def testResponseStreamEvent(self):
        """Test ResponseStreamEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
