# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_assistants_response import ListAssistantsResponse

class TestListAssistantsResponse(unittest.TestCase):
    """ListAssistantsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAssistantsResponse:
        """Test ListAssistantsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAssistantsResponse`
        """
        model = ListAssistantsResponse()
        if include_optional:
            return ListAssistantsResponse(
                object = 'list',
                data = [
                    openapi_client.models.assistant.Assistant(
                        id = '',
                        object = 'assistant',
                        created_at = 56,
                        name = '',
                        description = '',
                        model = '',
                        instructions = '',
                        tools = [
                            null
                            ],
                        tool_resources = openapi_client.models.assistant_object_tool_resources.AssistantObject_tool_resources(
                            code_interpreter = openapi_client.models.assistant_object_tool_resources_code_interpreter.AssistantObject_tool_resources_code_interpreter(
                                file_ids = [
                                    ''
                                    ], ),
                            file_search = openapi_client.models.assistant_object_tool_resources_file_search.AssistantObject_tool_resources_file_search(
                                vector_store_ids = [
                                    ''
                                    ], ), ),
                        metadata = {
                            'key' : ''
                            },
                        temperature = 1,
                        top_p = 1,
                        response_format = null, )
                    ],
                first_id = 'asst_abc123',
                last_id = 'asst_abc456',
                has_more = False
            )
        else:
            return ListAssistantsResponse(
                object = 'list',
                data = [
                    openapi_client.models.assistant.Assistant(
                        id = '',
                        object = 'assistant',
                        created_at = 56,
                        name = '',
                        description = '',
                        model = '',
                        instructions = '',
                        tools = [
                            null
                            ],
                        tool_resources = openapi_client.models.assistant_object_tool_resources.AssistantObject_tool_resources(
                            code_interpreter = openapi_client.models.assistant_object_tool_resources_code_interpreter.AssistantObject_tool_resources_code_interpreter(
                                file_ids = [
                                    ''
                                    ], ),
                            file_search = openapi_client.models.assistant_object_tool_resources_file_search.AssistantObject_tool_resources_file_search(
                                vector_store_ids = [
                                    ''
                                    ], ), ),
                        metadata = {
                            'key' : ''
                            },
                        temperature = 1,
                        top_p = 1,
                        response_format = null, )
                    ],
                first_id = 'asst_abc123',
                last_id = 'asst_abc456',
                has_more = False,
        )
        """

    def testListAssistantsResponse(self):
        """Test ListAssistantsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
