# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_transcription_response_stream_event import CreateTranscriptionResponseStreamEvent

class TestCreateTranscriptionResponseStreamEvent(unittest.TestCase):
    """CreateTranscriptionResponseStreamEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTranscriptionResponseStreamEvent:
        """Test CreateTranscriptionResponseStreamEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTranscriptionResponseStreamEvent`
        """
        model = CreateTranscriptionResponseStreamEvent()
        if include_optional:
            return CreateTranscriptionResponseStreamEvent(
                type = 'transcript.text.delta',
                delta = '',
                text = '',
                logprobs = [
                    openapi_client.models.transcript_text_done_event_logprobs_inner.TranscriptTextDoneEvent_logprobs_inner(
                        token = '',
                        logprob = 1.337,
                        bytes = [
                            56
                            ], )
                    ]
            )
        else:
            return CreateTranscriptionResponseStreamEvent(
                type = 'transcript.text.delta',
                delta = '',
                text = '',
        )
        """

    def testCreateTranscriptionResponseStreamEvent(self):
        """Test CreateTranscriptionResponseStreamEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
