# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_assistant_request import CreateAssistantRequest

class TestCreateAssistantRequest(unittest.TestCase):
    """CreateAssistantRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAssistantRequest:
        """Test CreateAssistantRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAssistantRequest`
        """
        model = CreateAssistantRequest()
        if include_optional:
            return CreateAssistantRequest(
                model = llama-3.1-8,
                name = '',
                description = '',
                instructions = '',
                reasoning_effort = 'medium',
                tools = [
                    null
                    ],
                tool_resources = openapi_client.models.create_assistant_request_tool_resources.CreateAssistantRequest_tool_resources(
                    code_interpreter = openapi_client.models.create_assistant_request_tool_resources_code_interpreter.CreateAssistantRequest_tool_resources_code_interpreter(
                        file_ids = [
                            ''
                            ], ),
                    file_search = openapi_client.models.create_assistant_request_tool_resources_file_search.CreateAssistantRequest_tool_resources_file_search(
                        vector_store_ids = [
                            ''
                            ],
                        vector_stores = [
                            openapi_client.models.create_assistant_request_tool_resources_file_search_vector_stores_inner.CreateAssistantRequest_tool_resources_file_search_vector_stores_inner(
                                chunking_strategy = openapi_client.models.create_assistant_request_tool_resources_file_search_vector_stores_inner_chunking_strategy.CreateAssistantRequest_tool_resources_file_search_vector_stores_inner_chunking_strategy(),
                                metadata = {
                                    'key' : ''
                                    }, )
                            ], ), ),
                metadata = {
                    'key' : ''
                    },
                temperature = 1,
                top_p = 1,
                response_format = None
            )
        else:
            return CreateAssistantRequest(
                model = llama-3.1-8,
        )
        """

    def testCreateAssistantRequest(self):
        """Test CreateAssistantRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
