# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.chat_api import ChatApi


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChatApi()

    def tearDown(self) -> None:
        pass

    def test_add_chat_completion(self) -> None:
        """Test case for add_chat_completion

        Adds a chat to existing conversation.
        """
        pass

    def test_create_chat_completion(self) -> None:
        """Test case for create_chat_completion

        Creates a chat conversation.
        """
        pass

    def test_delete_chat_completion(self) -> None:
        """Test case for delete_chat_completion

        Delete a stored chat completion.
        """
        pass


if __name__ == '__main__':
    unittest.main()
