# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.run_step_delta_object_delta_step_details import RunStepDeltaObjectDeltaStepDetails

class TestRunStepDeltaObjectDeltaStepDetails(unittest.TestCase):
    """RunStepDeltaObjectDeltaStepDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunStepDeltaObjectDeltaStepDetails:
        """Test RunStepDeltaObjectDeltaStepDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunStepDeltaObjectDeltaStepDetails`
        """
        model = RunStepDeltaObjectDeltaStepDetails()
        if include_optional:
            return RunStepDeltaObjectDeltaStepDetails(
                type = 'message_creation',
                message_creation = openapi_client.models.run_step_delta_step_details_message_creation_object_message_creation.RunStepDeltaStepDetailsMessageCreationObject_message_creation(
                    message_id = '', ),
                tool_calls = [
                    null
                    ]
            )
        else:
            return RunStepDeltaObjectDeltaStepDetails(
                type = 'message_creation',
        )
        """

    def testRunStepDeltaObjectDeltaStepDetails(self):
        """Test RunStepDeltaObjectDeltaStepDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
