# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.realtime_client_event_output_audio_buffer_clear import RealtimeClientEventOutputAudioBufferClear

class TestRealtimeClientEventOutputAudioBufferClear(unittest.TestCase):
    """RealtimeClientEventOutputAudioBufferClear unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RealtimeClientEventOutputAudioBufferClear:
        """Test RealtimeClientEventOutputAudioBufferClear
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RealtimeClientEventOutputAudioBufferClear`
        """
        model = RealtimeClientEventOutputAudioBufferClear()
        if include_optional:
            return RealtimeClientEventOutputAudioBufferClear(
                event_id = '',
                type = 'output_audio_buffer.clear'
            )
        else:
            return RealtimeClientEventOutputAudioBufferClear(
                type = 'output_audio_buffer.clear',
        )
        """

    def testRealtimeClientEventOutputAudioBufferClear(self):
        """Test RealtimeClientEventOutputAudioBufferClear"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
