# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.realtime_client_event import RealtimeClientEvent

class TestRealtimeClientEvent(unittest.TestCase):
    """RealtimeClientEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RealtimeClientEvent:
        """Test RealtimeClientEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RealtimeClientEvent`
        """
        model = RealtimeClientEvent()
        if include_optional:
            return RealtimeClientEvent(
                event_id = '',
                type = 'conversation.item.create',
                previous_item_id = '',
                item = openapi_client.models.realtime_conversation_item.RealtimeConversationItem(
                    id = '',
                    type = 'message',
                    object = 'realtime.item',
                    status = 'completed',
                    role = 'user',
                    content = [
                        openapi_client.models.realtime_conversation_item_content_inner.RealtimeConversationItem_content_inner(
                            type = 'input_audio',
                            text = '',
                            id = '',
                            audio = '',
                            transcript = '', )
                        ],
                    call_id = '',
                    name = '',
                    arguments = '',
                    output = '', ),
                item_id = '',
                content_index = 56,
                audio_end_ms = 56,
                audio = '',
                response_id = '',
                response = openapi_client.models.realtime_response_create_params.RealtimeResponseCreateParams(
                    modalities = [
                        'text'
                        ],
                    instructions = '',
                    voice = ash,
                    output_audio_format = 'pcm16',
                    tools = [
                        openapi_client.models.realtime_response_create_params_tools_inner.RealtimeResponseCreateParams_tools_inner(
                            type = 'function',
                            name = '',
                            description = '',
                            parameters = openapi_client.models.parameters.parameters(), )
                        ],
                    tool_choice = '',
                    temperature = 1.337,
                    max_response_output_tokens = null,
                    conversation = null,
                    metadata = {
                        'key' : ''
                        },
                    input = [
                        openapi_client.models.realtime_conversation_item_with_reference.RealtimeConversationItemWithReference(
                            id = '',
                            type = 'message',
                            object = 'realtime.item',
                            status = 'completed',
                            role = 'user',
                            content = [
                                openapi_client.models.realtime_conversation_item_content_inner.RealtimeConversationItem_content_inner(
                                    type = 'input_audio',
                                    text = '',
                                    id = '',
                                    audio = '',
                                    transcript = '', )
                                ],
                            call_id = '',
                            name = '',
                            arguments = '',
                            output = '', )
                        ], ),
                session = openapi_client.models.realtime_transcription_session_create_request.RealtimeTranscriptionSessionCreateRequest(
                    modalities = [
                        'text'
                        ],
                    input_audio_format = 'pcm16',
                    input_audio_transcription = openapi_client.models.realtime_transcription_session_create_request_input_audio_transcription.RealtimeTranscriptionSessionCreateRequest_input_audio_transcription(
                        model = 'llama-3.1-8',
                        language = '',
                        prompt = '', ),
                    turn_detection = openapi_client.models.realtime_transcription_session_create_request_turn_detection.RealtimeTranscriptionSessionCreateRequest_turn_detection(
                        type = 'server_vad',
                        eagerness = 'auto',
                        threshold = 1.337,
                        prefix_padding_ms = 56,
                        silence_duration_ms = 56,
                        create_response = True,
                        interrupt_response = True, ),
                    input_audio_noise_reduction = openapi_client.models.realtime_session_input_audio_noise_reduction.RealtimeSession_input_audio_noise_reduction(
                        type = 'near_field', ),
                    include = [
                        ''
                        ], )
            )
        else:
            return RealtimeClientEvent(
                type = 'conversation.item.create',
                item = openapi_client.models.realtime_conversation_item.RealtimeConversationItem(
                    id = '',
                    type = 'message',
                    object = 'realtime.item',
                    status = 'completed',
                    role = 'user',
                    content = [
                        openapi_client.models.realtime_conversation_item_content_inner.RealtimeConversationItem_content_inner(
                            type = 'input_audio',
                            text = '',
                            id = '',
                            audio = '',
                            transcript = '', )
                        ],
                    call_id = '',
                    name = '',
                    arguments = '',
                    output = '', ),
                item_id = '',
                content_index = 56,
                audio_end_ms = 56,
                audio = '',
                session = openapi_client.models.realtime_transcription_session_create_request.RealtimeTranscriptionSessionCreateRequest(
                    modalities = [
                        'text'
                        ],
                    input_audio_format = 'pcm16',
                    input_audio_transcription = openapi_client.models.realtime_transcription_session_create_request_input_audio_transcription.RealtimeTranscriptionSessionCreateRequest_input_audio_transcription(
                        model = 'llama-3.1-8',
                        language = '',
                        prompt = '', ),
                    turn_detection = openapi_client.models.realtime_transcription_session_create_request_turn_detection.RealtimeTranscriptionSessionCreateRequest_turn_detection(
                        type = 'server_vad',
                        eagerness = 'auto',
                        threshold = 1.337,
                        prefix_padding_ms = 56,
                        silence_duration_ms = 56,
                        create_response = True,
                        interrupt_response = True, ),
                    input_audio_noise_reduction = openapi_client.models.realtime_session_input_audio_noise_reduction.RealtimeSession_input_audio_noise_reduction(
                        type = 'near_field', ),
                    include = [
                        ''
                        ], ),
        )
        """

    def testRealtimeClientEvent(self):
        """Test RealtimeClientEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
