# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.computer_tool_call_output import ComputerToolCallOutput

class TestComputerToolCallOutput(unittest.TestCase):
    """ComputerToolCallOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComputerToolCallOutput:
        """Test ComputerToolCallOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComputerToolCallOutput`
        """
        model = ComputerToolCallOutput()
        if include_optional:
            return ComputerToolCallOutput(
                type = 'computer_call_output',
                id = '',
                call_id = '',
                acknowledged_safety_checks = [
                    openapi_client.models.computer_tool_call_safety_check.ComputerToolCallSafetyCheck(
                        id = '',
                        code = '',
                        message = '', )
                    ],
                output = openapi_client.models.computer_screenshot_image.ComputerScreenshotImage(
                    type = 'computer_screenshot',
                    image_url = '',
                    file_id = '', ),
                status = 'in_progress'
            )
        else:
            return ComputerToolCallOutput(
                type = 'computer_call_output',
                call_id = '',
                output = openapi_client.models.computer_screenshot_image.ComputerScreenshotImage(
                    type = 'computer_screenshot',
                    image_url = '',
                    file_id = '', ),
        )
        """

    def testComputerToolCallOutput(self):
        """Test ComputerToolCallOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
