# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.response_code_interpreter_call_in_progress_event import ResponseCodeInterpreterCallInProgressEvent

class TestResponseCodeInterpreterCallInProgressEvent(unittest.TestCase):
    """ResponseCodeInterpreterCallInProgressEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCodeInterpreterCallInProgressEvent:
        """Test ResponseCodeInterpreterCallInProgressEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCodeInterpreterCallInProgressEvent`
        """
        model = ResponseCodeInterpreterCallInProgressEvent()
        if include_optional:
            return ResponseCodeInterpreterCallInProgressEvent(
                type = 'response.code_interpreter_call.in_progress',
                output_index = 56,
                code_interpreter_call = openapi_client.models.code_interpreter_tool_call.Code interpreter tool call(
                    id = '',
                    type = 'code_interpreter_call',
                    code = '',
                    status = 'in_progress',
                    results = [
                        null
                        ], )
            )
        else:
            return ResponseCodeInterpreterCallInProgressEvent(
                type = 'response.code_interpreter_call.in_progress',
                output_index = 56,
                code_interpreter_call = openapi_client.models.code_interpreter_tool_call.Code interpreter tool call(
                    id = '',
                    type = 'code_interpreter_call',
                    code = '',
                    status = 'in_progress',
                    results = [
                        null
                        ], ),
        )
        """

    def testResponseCodeInterpreterCallInProgressEvent(self):
        """Test ResponseCodeInterpreterCallInProgressEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
