# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_certificates_response import ListCertificatesResponse

class TestListCertificatesResponse(unittest.TestCase):
    """ListCertificatesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCertificatesResponse:
        """Test ListCertificatesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCertificatesResponse`
        """
        model = ListCertificatesResponse()
        if include_optional:
            return ListCertificatesResponse(
                data = [
                    openapi_client.models.certificate.Certificate(
                        object = 'certificate',
                        id = '',
                        name = '',
                        created_at = 56,
                        certificate_details = openapi_client.models.certificate_certificate_details.Certificate_certificate_details(
                            valid_at = 56,
                            expires_at = 56,
                            content = '', ),
                        active = True, )
                    ],
                first_id = 'cert_abc',
                last_id = 'cert_abc',
                has_more = True,
                object = 'list'
            )
        else:
            return ListCertificatesResponse(
                data = [
                    openapi_client.models.certificate.Certificate(
                        object = 'certificate',
                        id = '',
                        name = '',
                        created_at = 56,
                        certificate_details = openapi_client.models.certificate_certificate_details.Certificate_certificate_details(
                            valid_at = 56,
                            expires_at = 56,
                            content = '', ),
                        active = True, )
                    ],
                has_more = True,
                object = 'list',
        )
        """

    def testListCertificatesResponse(self):
        """Test ListCertificatesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
