# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_key_list import ApiKeyList

class TestApiKeyList(unittest.TestCase):
    """ApiKeyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyList:
        """Test ApiKeyList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyList`
        """
        model = ApiKeyList()
        if include_optional:
            return ApiKeyList(
                object = 'list',
                data = [
                    openapi_client.models.admin_api_key.AdminApiKey(
                        object = 'organization.admin_api_key',
                        id = 'key_abc',
                        name = 'Administration Key',
                        redacted_value = 'sk-admin...def',
                        value = 'sk-admin-1234abcd',
                        created_at = 1711471533,
                        last_used_at = 1711471534,
                        owner = openapi_client.models.admin_api_key_owner.AdminApiKey_owner(
                            type = 'user',
                            object = 'organization.user',
                            id = 'sa_456',
                            name = 'My Service Account',
                            created_at = 1711471533,
                            role = 'owner', ), )
                    ],
                has_more = False,
                first_id = 'key_abc',
                last_id = 'key_xyz'
            )
        else:
            return ApiKeyList(
        )
        """

    def testApiKeyList(self):
        """Test ApiKeyList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
