# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_thread_and_run_request_tool_resources import CreateThreadAndRunRequestToolResources

class TestCreateThreadAndRunRequestToolResources(unittest.TestCase):
    """CreateThreadAndRunRequestToolResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateThreadAndRunRequestToolResources:
        """Test CreateThreadAndRunRequestToolResources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateThreadAndRunRequestToolResources`
        """
        model = CreateThreadAndRunRequestToolResources()
        if include_optional:
            return CreateThreadAndRunRequestToolResources(
                code_interpreter = openapi_client.models.create_assistant_request_tool_resources_code_interpreter.CreateAssistantRequest_tool_resources_code_interpreter(
                    file_ids = [
                        ''
                        ], ),
                file_search = openapi_client.models.assistant_object_tool_resources_file_search.AssistantObject_tool_resources_file_search(
                    vector_store_ids = [
                        ''
                        ], )
            )
        else:
            return CreateThreadAndRunRequestToolResources(
        )
        """

    def testCreateThreadAndRunRequestToolResources(self):
        """Test CreateThreadAndRunRequestToolResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
