# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.invite_list_response import InviteListResponse

class TestInviteListResponse(unittest.TestCase):
    """InviteListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InviteListResponse:
        """Test InviteListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InviteListResponse`
        """
        model = InviteListResponse()
        if include_optional:
            return InviteListResponse(
                object = 'list',
                data = [
                    openapi_client.models.invite.Invite(
                        object = 'organization.invite',
                        id = '',
                        email = '',
                        role = 'owner',
                        status = 'accepted',
                        invited_at = 56,
                        expires_at = 56,
                        accepted_at = 56,
                        projects = [
                            openapi_client.models.invite_projects_inner.Invite_projects_inner(
                                id = '',
                                role = 'member', )
                            ], )
                    ],
                first_id = '',
                last_id = '',
                has_more = True
            )
        else:
            return InviteListResponse(
                object = 'list',
                data = [
                    openapi_client.models.invite.Invite(
                        object = 'organization.invite',
                        id = '',
                        email = '',
                        role = 'owner',
                        status = 'accepted',
                        invited_at = 56,
                        expires_at = 56,
                        accepted_at = 56,
                        projects = [
                            openapi_client.models.invite_projects_inner.Invite_projects_inner(
                                id = '',
                                role = 'member', )
                            ], )
                    ],
        )
        """

    def testInviteListResponse(self):
        """Test InviteListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
