# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.project_api_key_owner import ProjectApiKeyOwner

class TestProjectApiKeyOwner(unittest.TestCase):
    """ProjectApiKeyOwner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectApiKeyOwner:
        """Test ProjectApiKeyOwner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectApiKeyOwner`
        """
        model = ProjectApiKeyOwner()
        if include_optional:
            return ProjectApiKeyOwner(
                type = 'user',
                user = openapi_client.models.project_user.ProjectUser(
                    object = 'organization.project.user',
                    id = '',
                    name = '',
                    email = '',
                    role = 'owner',
                    added_at = 56, ),
                service_account = openapi_client.models.project_service_account.ProjectServiceAccount(
                    object = 'organization.project.service_account',
                    id = '',
                    name = '',
                    role = 'owner',
                    created_at = 56, )
            )
        else:
            return ProjectApiKeyOwner(
        )
        """

    def testProjectApiKeyOwner(self):
        """Test ProjectApiKeyOwner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
