# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.realtime_transcription_session_create_response import RealtimeTranscriptionSessionCreateResponse

class TestRealtimeTranscriptionSessionCreateResponse(unittest.TestCase):
    """RealtimeTranscriptionSessionCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RealtimeTranscriptionSessionCreateResponse:
        """Test RealtimeTranscriptionSessionCreateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RealtimeTranscriptionSessionCreateResponse`
        """
        model = RealtimeTranscriptionSessionCreateResponse()
        if include_optional:
            return RealtimeTranscriptionSessionCreateResponse(
                client_secret = openapi_client.models.realtime_transcription_session_create_response_client_secret.RealtimeTranscriptionSessionCreateResponse_client_secret(
                    value = '',
                    expires_at = 56, ),
                modalities = [
                    'text'
                    ],
                input_audio_format = '',
                input_audio_transcription = openapi_client.models.realtime_transcription_session_create_response_input_audio_transcription.RealtimeTranscriptionSessionCreateResponse_input_audio_transcription(
                    model = 'llama-3.1-8',
                    language = '',
                    prompt = '', ),
                turn_detection = openapi_client.models.realtime_session_create_response_turn_detection.RealtimeSessionCreateResponse_turn_detection(
                    type = '',
                    threshold = 1.337,
                    prefix_padding_ms = 56,
                    silence_duration_ms = 56, )
            )
        else:
            return RealtimeTranscriptionSessionCreateResponse(
                client_secret = openapi_client.models.realtime_transcription_session_create_response_client_secret.RealtimeTranscriptionSessionCreateResponse_client_secret(
                    value = '',
                    expires_at = 56, ),
        )
        """

    def testRealtimeTranscriptionSessionCreateResponse(self):
        """Test RealtimeTranscriptionSessionCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
