# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.response_refusal_delta_event import ResponseRefusalDeltaEvent

class TestResponseRefusalDeltaEvent(unittest.TestCase):
    """ResponseRefusalDeltaEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseRefusalDeltaEvent:
        """Test ResponseRefusalDeltaEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseRefusalDeltaEvent`
        """
        model = ResponseRefusalDeltaEvent()
        if include_optional:
            return ResponseRefusalDeltaEvent(
                type = 'response.refusal.delta',
                item_id = '',
                output_index = 56,
                content_index = 56,
                delta = ''
            )
        else:
            return ResponseRefusalDeltaEvent(
                type = 'response.refusal.delta',
                item_id = '',
                output_index = 56,
                content_index = 56,
                delta = '',
        )
        """

    def testResponseRefusalDeltaEvent(self):
        """Test ResponseRefusalDeltaEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
