# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.project_rate_limit_list_response import ProjectRateLimitListResponse

class TestProjectRateLimitListResponse(unittest.TestCase):
    """ProjectRateLimitListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectRateLimitListResponse:
        """Test ProjectRateLimitListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectRateLimitListResponse`
        """
        model = ProjectRateLimitListResponse()
        if include_optional:
            return ProjectRateLimitListResponse(
                object = 'list',
                data = [
                    openapi_client.models.project_rate_limit.ProjectRateLimit(
                        object = 'project.rate_limit',
                        id = '',
                        model = '',
                        max_requests_per_1_minute = 56,
                        max_tokens_per_1_minute = 56,
                        max_images_per_1_minute = 56,
                        max_audio_megabytes_per_1_minute = 56,
                        max_requests_per_1_day = 56,
                        batch_1_day_max_input_tokens = 56, )
                    ],
                first_id = '',
                last_id = '',
                has_more = True
            )
        else:
            return ProjectRateLimitListResponse(
                object = 'list',
                data = [
                    openapi_client.models.project_rate_limit.ProjectRateLimit(
                        object = 'project.rate_limit',
                        id = '',
                        model = '',
                        max_requests_per_1_minute = 56,
                        max_tokens_per_1_minute = 56,
                        max_images_per_1_minute = 56,
                        max_audio_megabytes_per_1_minute = 56,
                        max_requests_per_1_day = 56,
                        batch_1_day_max_input_tokens = 56, )
                    ],
                first_id = '',
                last_id = '',
                has_more = True,
        )
        """

    def testProjectRateLimitListResponse(self):
        """Test ProjectRateLimitListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
