# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# coding: utf-8

"""
    IOT Solutions - Gen-AI Microservice APIs

    These REST APIs provide the capability to run inference on Qualcomm 9100 devices.

    The version of the OpenAPI document: 1.0.0
    
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.realtime_response import RealtimeResponse

class TestRealtimeResponse(unittest.TestCase):
    """RealtimeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RealtimeResponse:
        """Test RealtimeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RealtimeResponse`
        """
        model = RealtimeResponse()
        if include_optional:
            return RealtimeResponse(
                id = '',
                object = 'realtime.response',
                status = 'completed',
                status_details = openapi_client.models.realtime_response_status_details.RealtimeResponse_status_details(
                    type = 'completed',
                    reason = 'turn_detected',
                    error = openapi_client.models.realtime_response_status_details_error.RealtimeResponse_status_details_error(
                        type = '',
                        code = '', ), ),
                output = [
                    openapi_client.models.realtime_conversation_item.RealtimeConversationItem(
                        id = '',
                        type = 'message',
                        object = 'realtime.item',
                        status = 'completed',
                        role = 'user',
                        content = [
                            openapi_client.models.realtime_conversation_item_content_inner.RealtimeConversationItem_content_inner(
                                type = 'input_audio',
                                text = '',
                                id = '',
                                audio = '',
                                transcript = '', )
                            ],
                        call_id = '',
                        name = '',
                        arguments = '',
                        output = '', )
                    ],
                metadata = {
                    'key' : ''
                    },
                usage = openapi_client.models.realtime_response_usage.RealtimeResponse_usage(
                    total_tokens = 56,
                    input_tokens = 56,
                    output_tokens = 56,
                    input_token_details = openapi_client.models.realtime_response_usage_input_token_details.RealtimeResponse_usage_input_token_details(
                        cached_tokens = 56,
                        text_tokens = 56,
                        audio_tokens = 56, ),
                    output_token_details = openapi_client.models.realtime_response_usage_output_token_details.RealtimeResponse_usage_output_token_details(
                        text_tokens = 56,
                        audio_tokens = 56, ), ),
                conversation_id = '',
                voice = ash,
                modalities = [
                    'text'
                    ],
                output_audio_format = 'pcm16',
                temperature = 1.337,
                max_output_tokens = None
            )
        else:
            return RealtimeResponse(
        )
        """

    def testRealtimeResponse(self):
        """Test RealtimeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
