# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

services:
  qimsdk:
    image: softwarecenter.qualcomm.com/download/depot/services/iot-microservices/linux/qimsdk:1.0.3
    platform: arm64
    container_name: qimsdk-daisy-chain
    hostname: qimsdk-daisy-chain
    user: qimsdk
    restart: always
    environment:
      - XDG_RUNTIME_DIR=/dev/socket/weston
      - WAYLAND_DISPLAY=wayland-1
      - GST_PLUGIN_SCANNER=/usr/lib/aarch64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
      - GST_DEBUG_NO_COLOR=1
      - GST_DEBUG=2
    command: bash qimsdk_daisy_chain.sh
    volumes:
      - /etc/labels:/etc/labels
      - /etc/media:/etc/media
      - /etc/models:/etc/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - qualcomm.com/device=cdi-hw-acc
    network_mode: host
