services:
  node-cck: # Cloud Connect Service Kafka
    platform: ${TARGET_ARCH}
    build:
      context: ./../../cloud-connect-kafka/nodejs/
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=${BUILD_TYPE}
    image: ${KAFKA_IMAGE}
    container_name: node-cck
    restart: "always"
    network_mode: "host"
    environment:
      - BUILD_TYPE=${BUILD_TYPE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
    volumes:
      - ${CERTIFICATES_DIR}:/var/ssl:ro
      - ${CONFIG_DIR}:/home/node/Cloud_Connect_Service/config:ro
      - ${IT_COVERAGE_DIR}:/home/node/Cloud_Connect_Service/coverage:rw 
      
  node-ccm: # Cloud Connect Service Mqtt
    platform: ${TARGET_ARCH}
    build:
      context: ./../../cloud-connect-mqtt/nodejs/
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=${BUILD_TYPE}
    image: ${MQTT_IMAGE}
    container_name: node-ccm
    restart: "always"
    network_mode: "host"
    environment:
      - BUILD_TYPE=${BUILD_TYPE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
    volumes:
      - ${CERTIFICATES_DIR}:/var/ssl:ro
      - ${CONFIG_DIR}:/home/node/Cloud_Connect_Service/config:ro
      - ${IT_COVERAGE_DIR}:/home/node/Cloud_Connect_Service/coverage:rw
  
  node-cck-ut: # Cloud Connect Service Kafka UT
    platform: ${TARGET_ARCH}
    build:
      context: ./../../cloud-connect-kafka/nodejs/
      dockerfile: test.Dockerfile
    image: node_cloud-connect-test-kafka:1.0.1
    container_name: node-cck-ut
    network_mode: "host"
    volumes:
      - ${UT_COVERAGE_DIR}:/home/node/Cloud_Connect_Service/coverage:rw
      - ${UT_REPORTS_DIR}:/home/node/Cloud_Connect_Service/reports:rw
      
  node-ccm-ut: # Cloud Connect Service Mqtt UT
    platform: ${TARGET_ARCH}
    build:
      context: ./../../cloud-connect-mqtt/nodejs/
      dockerfile: test.Dockerfile
    image: node_cloud-connect-test-mqtt:1.0.1
    container_name: node-ccm-ut
    network_mode: "host"
    volumes:
      - ${UT_COVERAGE_DIR}:/home/node/Cloud_Connect_Service/coverage:rw
      - ${UT_REPORTS_DIR}:/home/node/Cloud_Connect_Service/reports:rw

  c-ccm: # Cloud Connect Service
    platform: ${TARGET_ARCH}
    build:
      context: ./../../cloud-connect-mqtt/c/
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=${BUILD_TYPE}
    image: ${MQTT_IMAGE}
    container_name: c-ccm
    restart: "always"
    network_mode: "host"
    environment:
      - BUILD_TYPE=${BUILD_TYPE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
    volumes:
       # The path on the container is fixed, and is configurable via fluentbit configuration.
       # If it needs a change, update the fluentbit configuration, and corresponding logrotate configuration as well (if implemneted)
       # The path on the host will be used to create the logs. It must have enough storage as per mentioned int he fluent-bit configuration.
      - ${CERTIFICATES_DIR}:/var/ssl:ro
      - ${CONFIG_DIR}:/app/config:ro
      - ${IT_COVERAGE_DIR}:/app/mqtt_coverage:rw

  c-cck: # Cloud Connect Service
    platform: ${TARGET_ARCH}
    build:
      context: ./../../cloud-connect-kafka/c/
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=${BUILD_TYPE}
    image: ${KAFKA_IMAGE}
    container_name: c-cck
    restart: "always"
    network_mode: "host"
    environment:
      - BUILD_TYPE=${BUILD_TYPE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - BROKER_HOST=${BROKER_HOST}
      - BROKER_PORT=${BROKER_PORT}
    volumes:
       # The path on the container is fixed, and is configurable via fluentbit configuration.
       # If it needs a change, update the fluentbit configuration, and corresponding logrotate configuration as well (if implemneted)
       # The path on the host will be used to create the logs. It must have enough storage as per mentioned int he fluent-bit configuration.
      - ${CERTIFICATES_DIR}:/var/ssl:ro
      - ${CONFIG_DIR}:/app/config:ro
      - ${IT_COVERAGE_DIR}:/app/kafka_coverage:rw

  c-ccm-ut:
    platform: ${TARGET_ARCH}
    build:
      context: ./../../cloud-connect-mqtt/c/
      dockerfile: test.Dockerfile
    image: c_cloud-connect-test-mqtt:1.0.1
    container_name: c-ccm-ut
    network_mode: "host"
    volumes:
      - ${CONFIG_DIR}:/app/config:ro
      - ${CERTIFICATES_DIR}:/var/ssl:ro
      - ${UT_COVERAGE_DIR}:/app/mqtt_ut_coverage:rw
      - ${UT_REPORTS_DIR}:/app/mqtt_ut_report:rw

  c-cck-ut:
    platform: ${TARGET_ARCH}
    build:
      context: ./../../cloud-connect-kafka/c/
      dockerfile: test.Dockerfile
    image: c_cloud-connect-test-kafka:1.0.1
    container_name: c-cck-ut
    network_mode: "host"
    volumes:
      - ${CONFIG_DIR}:/app/config:ro
      - ${CERTIFICATES_DIR}:/var/ssl:ro
      - ${UT_COVERAGE_DIR}:/app/kafka_ut_coverage:rw
      - ${UT_REPORTS_DIR}:/app/kafka_ut_report:rw    