# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

services:
  nginx:
    image: nginx:1.27.2-alpine
    platform: arm64
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      - ~/configs/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ~/configs/nginx/solutions/people-analytics-api.conf:/etc/nginx/solutions/people-analytics-api.conf
  mariadb:
    image: mariadb:11.6.2
    platform: arm64
    container_name: mariadb
    hostname: mariadb
    restart: always
    volumes:
      - mariadbVolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretpw
    network_mode: host
  redis:
    image: redis:7.2.4-alpine
    platform: arm64
    container_name: redis
    hostname: redis
    restart: always
    command: redis-server --loglevel notice --notify-keyspace-events Kh
    network_mode: host
  people-analytics-api:
    image: artifacts.codelinaro.org/iot-solutions-microservices/people-analytics-api:latest
    platform: arm64
    container_name: people-analytics-api
    depends_on:
      - redis
      - mariadb
      - nginx
    restart: always
    environment:
      - redisHost=172.17.0.1
      - mariadbHost=172.17.0.1
      - mariadbPass=secretpw
      - redisPAAlertsChannel=${REDIS_ALERTS_CHANNEL:-people-analytics.alerts}
      - redisPAAnalyticsChannel=${REDIS_ANALYTICS_CHANNEL:-people-analytics.analytics}
      - redisCameraUpdates=${REDIS_CAMERA_UPDATES_CHANNEL:-camera-api.updates}
    expose:
      - '8080'
    network_mode: host
  people-analytics-server:
    image: artifacts.codelinaro.org/iot-solutions-microservices/people-analytics-server:latest
    platform: arm64
    container_name: people-analytics-server
    depends_on:
      - redis
      - mariadb
    restart: always
    environment:
      - REDIS_HOST=172.17.0.1
      - REDIS_DETECTION_CHANNEL_PREFIX=${REDIS_DETECTION_CHANNEL_PREFIX:-detection.ppe}
      - ALERT_CHANNEL=${REDIS_ALERTS_CHANNEL:-people-analytics.alerts}
      - ANALYTICS_CHANNEL=${REDIS_ANALYTICS_CHANNEL:-people-analytics.analytics}
      - UPDATES_CHANNEL=${REDIS_UPDATES_CHANNEL:-people-analytics.updates}
      - MARIADB_PASSWORD=secretpw
      - MARIADB_HOST=172.17.0.1
      - MARIADB_PORT=3306
      - MARIADB_USER=root
      - MARIADB_DEFAULT=iot_solutions
      - DEFAULT_HEATMAP_TABLE=heatmap_statistics
      - DEFAULT_COUNT_TABLE=count_statistics
      - DEFAULT_HEATMAP_ROWS=64
      - DEFAULT_HEATMAP_COLS=64
    network_mode: host
  qimsdk:
    image: softwarecenter.qualcomm.com/download/depot/services/iot-microservices/linux/qimsdk:1.0.5
    platform: arm64
    container_name: qimsdk-ppe
    hostname: qimsdk-ppe
    user: qimsdk
    restart: always
    environment:
      - XDG_RUNTIME_DIR=/dev/socket/weston
      - WAYLAND_DISPLAY=wayland-1
      - GST_PLUGIN_SCANNER=/usr/lib/aarch64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
      - GST_DEBUG_NO_COLOR=1
      - ADSP_LIBRARY_PATH=\"/usr/lib/dsp/cdsp;/usr/lib/dsp/cdsp1;${ADSP_LIBRARY_PATH}\"
      - GST_DEBUG=2
      - INPUT_TYPE=${INPUT_TYPE:-video}
      - INPUT_URL=${INPUT_URL:-/opt/sample-videos/people_sample_video.ts}
      - REDIS_DETECTION_CHANNEL=${REDIS_DETECTION_CHANNEL_PREFIX:-detection.ppe}:0
      - MODEL_PATH_PERSON=${MODEL_PATH_PERSON:-/etc/models/foot_track_net_quantized.tflite}
      - LABELS_PATH_PERSON=${LABELS_PATH_PERSON:-/opt/labels/foot_track_net.json}
      - SETTINGS_PATH_PERSON=${SETTINGS_PATH_PERSON:-/opt/labels/foot_track_net_settings.json}
      - MODEL_PATH_PPE=${MODEL_PATH_PPE:-/etc/models/gear_guard_net_quantized.tflite}
      - LABELS_PATH_PPE=${LABELS_PATH_PPE:-/opt/labels/ppe_labels.json}
      - REDIS_OUT_PORT=${REDIS_OUT_PORT:-6379}
      - OUT_PORT=${OUT_PORT:-8900}
    command: bash qimsdk_ppe.sh
    volumes:
      - /etc/labels:/etc/labels
      - /etc/media:/etc/media
      - /etc/models:/etc/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - qualcomm.com/device=cdi-hw-acc
    network_mode: host
volumes:
  mariadbVolume: null
